### ISSUE TITLE
서버 개수 미설정시 '0'으로 표시

### ISSUE THREAD

**Issue by GPM567** [koreanbots/koreanbots#10]
## 재현방법
어떻게하면 발생시킬 수 있나요?
서버 개수가 설정되어 있지 않은 봇 페이지로 들어갑니다.

## 예상되는 정상적인 동작
정상이라면 어떻게 되야하나요?
'0 서버'로 표시되어야 합니다.

## 발생한 문제
어떤 문제가 발생하나요?
'0'으로 표시됩니다.

## 클라이언트 버전
클라이언트 버전을 알려주세요!
[빌드정보] 버전: 0.2.3 해시: ad1b421d43c3b44c835a7e97ca9f1e85825e887d

## 사양
OS 정보와 브라우저의 버전을 알려주세요!
버전 81.0.4044.129(공식 빌드) (64비트)
Windows 10 Pro 버전 1909

## 확인
- [x] 중복되는 이슈는 없나요?
- [x] 해당 버그를 다시 발생시킬 수 있나요?

**Comment by wonderlandpark** [comment]
재현할 수 있습니다. 서버 수가 설정되지 않은 페이지에서 `0` 으로 표시됩니다.

**Comment by wonderlandpark** [comment]
수정했습니다!
