### ISSUE TITLE
[제안] 첫 페이지에는 검색만 나오면 좋을것같아요

### ISSUE THREAD

**Issue by minibox724** [koreanbots/koreanbots#100]
## 기능 설명
> 어떤 기능인가요?
구글처럼 첫페이지에는 딱 광고도 없이 검색창만 나오고 스크롤을 딱 하나만 해도 자연스럽게 자동스크롤을 하면서 하트 랭킹.. 새로 추가된 봇..들이 나오는거에요

## 필요한 이유
> 해당 기능을 왜 추가해야하나요?
먼저 디자인으로 감탄을 받을 수 있고 1920*1080의 전체화면으로 웹사이트에 가면 광고가 먼저 있고 그 밑에 애매하게 `카테고리로 빠르게 찾아보기:` 가 있는데 더 심플하고 깔끔해질것같아요

## 기대 효과
> 해당 기능을 추가하면 어떤 이점이 발생하나요?
디자인으로 인한 편안함

## 확인
- [x] 중복되는 제안사항은 없나요?
- [x] 현실성 있는 제안인가요?

<!--
마크다운 체크박스 문법입니다.
[x] - 체크
[ ] - 체크하지 않음
으로 작성해주세요.
>

**Comment by wonderlandpark** [comment]
고려하고 있는 사안중 하나입니다. 개발진은 많은 시도들을 해보고 있습니다. 고려해보겠습니다.
