### ISSUE TITLE
[제안] 검색했을때 이상하게 표시됨

### ISSUE THREAD

**Issue by kiki7000** [koreanbots/koreanbots#101]
## 재현방법
> 아무거나 검색해줍니다
![image](https://user-images.githubusercontent.com/51841836/89123960-5628e300-d50e-11ea-902b-60244368db70.png)

## 예상되는 정상적인 동작
> 대충 아래 사진처럼 됩니다
![image](https://user-images.githubusercontent.com/51841836/89123968-60e37800-d50e-11ea-84b9-3746230187cf.png)

## 발생한 문제
> 아래 사진처럼 됩니다
![image](https://user-images.githubusercontent.com/51841836/89123979-6e006700-d50e-11ea-850b-85a36e30d36f.png)

## 클라이언트 버전
> a67d3c417e98f911a303e27d72376ab8fbc7c557

## 사양
> 파폭 78.0.2

## 확인
- [x] 중복되는 이슈는 없나요?
- [x] 해당 버그를 다시 발생시킬 수 있나요?

**Comment by wonderlandpark** [comment]
CR 1.2 Chrome Beta 85

**Comment by kiki7000** [comment]
https://github.com/koreanbots/client/pull/32
테스트는 안해봤지만 한번 PR 했어요
비효율적인 코드인가요? ㅋ

**Comment by kms0219kms** [comment]
Chrome Canary, Whale, Edge (Chromium Edition)에서 동일한 증상입니다

**Comment by kms0219kms** [comment]
![image](https://user-images.githubusercontent.com/67222970/89407518-7d4e0300-d70e-11ea-8c48-0f130a5adfcc.png)

**Comment by SaidBySolo** [comment]
fix in https://github.com/koreanbots/client/pull/33
