### ISSUE TITLE
[제안] 봇 추가 페이지 제출 버튼이랑 푸터랑 마진 넣어주세요

### ISSUE THREAD

**Issue by kiki7000** [koreanbots/koreanbots#104]
## 기능 설명
> [봇 추가 페이지](https://koreanbots.dev/addbot) 제출 버튼과 푸터랑 마진 넣어주세요(표현이 조금 이상한가요?)

## 필요한 이유
> 아래 사진 처럼 좀 불편(?)하고 예쁘지 않습니다
![image](https://user-images.githubusercontent.com/51841836/89396012-0124e100-d749-11ea-94ce-7413dad13ea1.png)

## 기대 효과
> 아래 사진처럼 조금 더 나아집니다
![image](https://user-images.githubusercontent.com/51841836/89396400-798ba200-d749-11ea-8928-69f8720b3973.png)

## 확인
- [x] 중복되는 제안사항은 없나요?
- [x] 현실성 있는 제안인가요?

**Comment by ReDesignedJP** [comment]
@wonderlandpark

**Comment by wonderlandpark** [comment]
Too minor
