### ISSUE TITLE
[TYPO] 오타

### ISSUE THREAD

**Issue by kiki7000** [koreanbots/koreanbots#120]
## 재현방법
> 걍 koreanbots.dev에 접속

## 예상되는 정상적인 동작
> 아래처럼 따끈따끈이라 표기되야함
![image](https://user-images.githubusercontent.com/51841836/91420107-295ab800-e88f-11ea-978e-5c5ce2c77def.png)

## 발생한 문제
> 따**근** 오타
![image](https://user-images.githubusercontent.com/51841836/91420006-0af4bc80-e88f-11ea-8228-ae53e5945769.png)

## 클라이언트 버전
> 89c1a4cef7b01d3c87c39c1d6063a4a16389892d

## 사양
> 파폭

## 확인
- [x] 중복되는 이슈는 없나요?
- [x] 해당 버그를 다시 발생시킬 수 있나요?

<!--
마크다운 체크박스 문법입니다.
[x] - 체크
[ ] - 체크하지 않음
으로 작성해주세요.
>

**Comment by kiki7000** [comment]
@iu-bot 오타라 모든 환경에서도 공통하게 오타가 보일걸요

**Comment by samsunghappytree123** [comment]
@kiki7000 저거 봇인데요

**Comment by SaidBySolo** [comment]
close in https://github.com/koreanbots/client/pull/44

**Comment by kiki7000** [comment]
? 봇이네
