### ISSUE TITLE
[버그] 봇 등록 버그

### ISSUE THREAD

**Issue by codemaker-dev** [koreanbots/koreanbots#121]
## 재현방법
한국 디스코드 봇 리스트에 봇 추가를 신청한다.
신청했던 봇을 삭제한다.
## 예상되는 정상적인 동작
봇을 삭제하면 신청중이었던 내역이 사라져야함
## 발생한 문제
봇 신청중에 신청한 봇을 삭제하면 새로운 봇을 등록할 수 없게 됨

## 클라이언트 버전
> 클라이언트 버전을 알려주세요!
1.2.0
클라이언트 버전을 가져오실 줄 모르신다면 아래 링크를 참고해주세요

https://github.com/koreanbots/docs/blob/master/version.md
-->
## 사양
> OS 정보와 브라우저의 버전을 알려주세요!
크롬, windows 8.1

## 확인
- [ ] 중복되는 이슈는 없나요?
- [ ] 해당 버그를 다시 발생시킬 수 있나요?

<!--
마크다운 체크박스 문법입니다.
[x] - 체크
[ ] - 체크하지 않음
으로 작성해주세요.
>

**Comment by wonderlandpark** [comment]
NAB, Intended Feature
