### ISSUE TITLE
[버그] API 설명이 잘못됨

### ISSUE THREAD

**Issue by tlfn** [koreanbots/koreanbots#129]
## 재현방법
> 다음 사이트에 들어갑니다: https://koreanbots.dev/api/api/bots

## 예상되는 정상적인 동작
> vanity: string|false
봇의 VANITY URL (해당 항목은 boosted 항목 또는 trusted 항목이 허용되어있는 경우에만 적용됩니다)
banner: string|false
봇의 배너 링크 (미리보기 배경) (해당 항목은 boosted 항목 또는 trusted 항목이 허용되어있는 경우에만 적용됩니다)
bg: string|false
봇의 배경 링크 (세부설명 배경) (해당 항목은 boosted 항목 또는 trusted 항목이 허용되어있는 경우에만 적용됩니다)

위에 수정한 글처럼 설명 되어야합니다.

## 발생한 문제
부스터의 티어 2 혜택을 KOREANBOTS로부터 인증된 봇에게 무상으로 제공하지만 API에서는 다르게 서술되어있습니다.

> vanity: string|false
봇의 VANITY URL (해당 항목은 boosted 항목이 허용되어있는 경우에만 적용됩니다)
banner: string|false
봇의 배너 링크 (미리보기 배경) (해당 항목은 boosted 항목이 허용되어있는 경우에만 적용됩니다)
bg: string|false
봇의 배경 링크 (세부설명 배경) (해당 항목은 boosted 항목이 허용되어있는 경우에만 적용됩니다)

위 설명에서 boosted 가 true 일 때 뿐만 아니라 trusted 가 true 일 때도 사용될 수 있습니다.

## 클라이언트 버전
> 2872d357df5756e03c2a3a29b857563c4700c425

## 사양
> Windows 10, Microsoft Edge

## 확인
- [x] 중복되는 이슈는 없나요?
- [x] 해당 버그를 다시 발생시킬 수 있나요?

**Comment by wonderlandpark** [comment]
Too minor typo issue.
