### ISSUE TITLE
[버그] 광고

### ISSUE THREAD

**Issue by samsunghappytree123** [koreanbots/koreanbots#134]
## 재현방법
> 어떻게하면 발생시킬 수 있나요?
광고가 있는 모든 페이지에 들어가면 됩니다.

## 예상되는 정상적인 동작
> 정상이라면 어떻게 되야하나요?
광고가 크기가 맞게 나타나야합니다.

## 발생한 문제
> 어떤 문제가 발생하나요?
광고의 크기가 맞지 않습니다.
![2E85B00C-5D34-4ECD-BFA5-4631C2BD235C](https://user-images.githubusercontent.com/58595445/96799316-d2600200-143d-11eb-8b4c-68a8c9957b7f.png)
![8BB146C7-40E8-4480-AD82-36E036681099](https://user-images.githubusercontent.com/58595445/96799340-e0ae1e00-143d-11eb-9b82-5d49a9e34457.png)

## 클라이언트 버전
> 클라이언트 버전을 알려주세요!
+ [빌드정보] 버전: 1.2.0 해시: 886986b9f22f028ea899244b106ce05765dfb8e7

## 사양
> OS 정보와 브라우저의 버전을 알려주세요!
+ ios 14.2 / 네이버 웨일

## 확인
- [x] 중복되는 이슈는 없나요?
- [x] 해당 버그를 다시 발생시킬 수 있나요?

<!--
마크다운 체크박스 문법입니다.
[x] - 체크
[ ] - 체크하지 않음
으로 작성해주세요.
>

**Comment by wonderlandpark** [comment]
버그가 수정되었습니다.

부스터에 광고 삭제 혜택은 삭제될 예정입니다.
