### ISSUE TITLE
[버그] 토큰 복사가 되지 않음

### ISSUE THREAD

**Issue by Entick9** [koreanbots/koreanbots#141]
## 재현방법
> 관리패널 ->(봇) 관리하기->(토큰) 복사히기

## 예상되는 정상적인 동작
> 토큰이 복사되고, 붙여넣을 수 있어야 합니다

## 발생한 문제
> 복사가 되지 않습니다

## 클라이언트 버전
> 클라이언트 버전을 확인하려 다음 링크로 들어갔으나 사이트가 존재하지 않아(404 error) 모르겠습니다
https://github.com/koreanbots/docs/blob/master/version.md

## 사양
> macOS 11.1 (Big Sur), 네이버 웨일 2.8.105.22 (64-bit)

## 확인
- [x] 중복되는 이슈는 없나요?
- [x] 해당 버그를 다시 발생시킬 수 있나요?

<!--
마크다운 체크박스 문법입니다.
[x] - 체크
[ ] - 체크하지 않음
으로 작성해주세요.
>

**Comment by samsunghappytree123** [comment]
클라이언트 버전은 [koreeanbots 사이트](https://koreanbots.dev) 들어가셔서 큰솔 보시면 상단에 나와있습니다

**Comment by wonderlandpark** [comment]
복사하기 누르시고 alert창의 확인을 눌러주시면 복사됩니다.

**Comment by SaidBySolo** [comment]
재현할수없습니다.

**Comment by Helloyunho** [comment]
macOS Big Sur 11.1, Microsoft Edge 87.0.664.66(네이버 웨일과 같은 크로미움 기반)에서 재현 가능합니다.

클라이언트 버전: 58d991386175a23d8a23b721bf3ec5664fe7a0ff

**Comment by wonderlandpark** [comment]
alert 확인 누르시면 복사됩니다 ^^^7

**Comment by Helloyunho** [comment]
![bug](https://user-images.githubusercontent.com/10192625/102649394-6c2cfc80-41ac-11eb-9791-e41cf9223cf4.gif)
증거 gif 드리겠습니다.

**Comment by wonderlandpark** [comment]
# 재현 가능한 플랫폼

- [ ] ~~Chrome~~
- [ ] Whale (2/3 approves)
- [ ] Safari

**Comment by wonderlandpark** [comment]
CNR, Windows 10 Home, Whale 2.8.108.15, Client Hash 58d991386175a23d8a23b721bf3ec5664fe7a0ff

**Comment by wonderlandpark** [comment]
![Uploading asdfasdf.gif…]()

**Comment by wonderlandpark** [comment]
![asdfasdf](https://user-images.githubusercontent.com/31924512/102674075-0191b600-41d8-11eb-9c17-d242c1407ee0.gif)

**Comment by wonderlandpark** [comment]
CNR, macOS Big Sur 11.1, Safari 14.0.2(16610.3.7.1.9)

**Comment by wonderlandpark** [comment]
CR, macOS Big Sur 11.1 2.8.108.15 (64-bit)

**Comment by SaidBySolo** [comment]
#125 참조.

2.0에 픽스될 예정입니다.

**Comment by wonderlandpark** [comment]
CR, macOS Big Sur 11.1 Chrome 87.0.4280.88

**Comment by wonderlandpark** [comment]
macOS + 크로미움 브라우저의 조합에서 발생하는 것으로 보입니다.

**Comment by wonderlandpark** [comment]
```js
Uncaught (in promise) DOMException: Document is not focused.
```
