### ISSUE TITLE
[버그] 서버 부스트 유저에대한 봇 커스텀 표지사진 순위표시 오류

### ISSUE THREAD

**Issue by Muzihuzi** [koreanbots/koreanbots#142]
## 재현방법
> 어떻게하면 발생시킬 수 있나요?
서버 부스트 유저에게 제공되는 커스텀 봇 표지이미지 기능이 적용된 봇의경우 순위가 하얀글씨로 표시되어 보이지 않습니다

## 예상되는 정상적인 동작
> 정상이라면 어떻게 되야하나요?
순위가 검정색으로 표시되어야 함

## 발생한 문제
> 어떤 문제가 발생하나요?
![bug.png](https://cdn.trinets.xyz/d/~k8TbF3jbe.png)

## 클라이언트 버전
> 클라이언트 버전을 알려주세요!
[빌드 정보] 버전: 1.2.0 해시: 58d991386175a23d8a23b721bf3ec5664fe7a0ff

## 사양
> OS 정보와 브라우저의 버전을 알려주세요!
Google Chrome
87.0.4280.88 (Official Build) (64-bit) (cohort: Stable)
Revision | 89e2380a3e36c3464b5dd1302349b1382549290d-refs/branch
Windows 10 Pro OS Version 1909 (Build 18363.1256)
## 확인
- [x] 중복되는 이슈는 없나요?
- [x] 해당 버그를 다시 발생시킬 수 있나요?

<!--
마크다운 체크박스 문법입니다.
[x] - 체크
[ ] - 체크하지 않음
으로 작성해주세요.
>

**Comment by wonderlandpark** [comment]
Duplicate of #128
