### ISSUE TITLE
[버그] 페이지 컨트롤러 우측으로 튀어나감

### ISSUE THREAD

**Issue by comjun04** [koreanbots/koreanbots#18]
## 재현방법
모바일 메인 페이지 맨 밑으로 이동합니다.
페이지 컨트롤러를 관찰합니다.

## 예상되는 정상적인 동작
페이지 컨트롤러가 중앙에 있어야 합니다.

## 발생한 문제
다음과 같이 페이지 컨트롤러가 오른쪽 끝으로 튀어 나갑니다.
![Capture+_2020-05-04-23-46-19](https://user-images.githubusercontent.com/30339539/80979069-da14f580-8e61-11ea-9ac8-c2f44425d29c.png)

## 클라이언트 버전
v0.5.1

## 사양
Android 8.0 (Oreo)
Chrome mobile 81

## 확인
- [x] 중복되는 이슈는 없나요?
- [x] 해당 버그를 다시 발생시킬 수 있나요?

**Comment by wonderlandpark** [comment]
CNR, Android 9, LG Q9
![Screenshot_20200504-235648](https://user-images.githubusercontent.com/31924512/80980099-34628600-8e63-11ea-8e42-6350436d1e97.png)
 
디바이스에 따라 다른거 같습니다.
디바이스 추가 정보와 스크린 길이를 제공해주시면 감사하겠습니다

**Comment by comjun04** [comment]
@wonderlandpark 테스트한 디바이스: LG G6, 1440x2880

**Comment by wonderlandpark** [comment]
Approved Will Fix
