### ISSUE TITLE
[버그] 아카이브된 봇 초대가능

### ISSUE THREAD

**Issue by ReDesignedJP** [koreanbots/koreanbots#21]
## 재현방법
어떻게하면 발생시킬 수 있나요?
봇 아카이브 및 투표 후 프로필에서 하트를 남긴봇 섹션
## 예상되는 정상적인 동작
정상이라면 어떻게 되야하나요?
초대버튼 비활성화 

## 발생한 문제
초대버튼이 활성화 되있습니다.

## 클라이언트 버전
52f41af0a85bd5991059fe001a117824e1dab9e7

## 사양
Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/81.0.4044.129 Safari/537.36

## 확인
- [x] 중복되는 이슈는 없나요?
- [x] 해당 버그를 다시 발생시킬 수 있나요?

**Comment by comjun04** [comment]
Can Reproduce. 재현 가능합니다.
![Capture+_2020-05-06-22-08-39](https://user-images.githubusercontent.com/30339539/81180626-428cdf80-8fe6-11ea-937b-65a9113ec2ec.png)

**Comment by wonderlandpark** [comment]
Approved.
