### ISSUE TITLE
건의 하트 리스트

### ISSUE THREAD

**Issue by minibox724** [koreanbots/koreanbots#22]
누가 추천을 눌렀는지가 담겨있는 리스트가 있으면 좋을것 같아요
리스트 안에는 추천을 누른 유저들의 아이디가 있는식으로요

**Comment by SaidBySolo** [comment]
제생각은 좋지않은것같습니다.
이미 Voted 엔드포인트로 유저의 투표여부를 알수있어서 
엔드포인트를 활용해서 개발자가 해당 엔드포인트를 활용해 충분히 리스트 항목을 만들수있습니다.

**Comment by wonderlandpark** [comment]
Received Down Votes. Denied
