### ISSUE TITLE
[TODO] 신고 추가

### ISSUE THREAD

**Issue by wonderlandpark** [koreanbots/koreanbots#23]
봇별 페이지에 신고 기능을 추가할 필요가 있습니다.

**Comment by wonderlandpark** [comment]
Self Approved

**Comment by GPM567** [comment]
봇 신고는 계속 가능한가요?
혹은 계정당 1번 가능한가요?
혹은 쿨타임(?)이 있나요?

**Comment by wonderlandpark** [comment]
@GPM567 아직 정해진건 없지만, 쿨타임은 따로 두지 않을 생각입니다.

**Comment by GPM567** [comment]
@wonderlandpark 그렇다면 신고를 계속할 수 있지 않나요?
(ex. 1초에 1번씩)

**Comment by minibox724** [comment]
> @wonderlandpark 그렇다면 신고를 계속할 수 있지 않나요?
> (ex. 1초에 1번씩)

자동으로 신고를 처리하는게 아니라면 큰 상관은 없을것같아요

**Comment by wonderlandpark** [comment]
@GPM567 그러면 신고 라우트는 별도의 레이트리밋을 적용하겠습니다!

**Comment by GPM567** [comment]
넵 감사합니다!

**Comment by kijk2869** [comment]
차선책, 구현하지 않고 디스코드 서버에서 운영,
혹은 새로운 레포지토리를 생성해 이슈 템플릿으로 운영

**Comment by wonderlandpark** [comment]
@kijk2869  불편한 점도 있고 그렇게 구현이 어려운 기능도 아니니, 구현해도 됩니다.

**Comment by wonderlandpark** [comment]
https://github.com/koreanbots/client/commit/d64937dd0c349a0ea59d42e8a917de1adce1a208 에서 구현
