### ISSUE TITLE
[버그] 로그인이 되어 있다고 위에 뜨는데도 다시 재로그인됩니다.

### ISSUE THREAD

**Issue by samsunghappytree123** [koreanbots/koreanbots#24]
## 재현방법
어떻게하면 발생시킬 수 있나요?
다른 창을 키거나 로그인했던 창을 끄고 몇시간 뒤에 다시 재접속하면 나옵니다.

## 예상되는 정상적인 동작
정상이라면 어떻게 되야하나요?
로그인하라고 뜰 것 같네요,

## 발생한 문제
어떤 문제가 발생하나요?
프로필 자리에는 로그인 되었다고 뜨는데 하트를 누르려면 세션 만료라고 뜹니다.

## 클라이언트 버전
클라이언트 버전을 알려주세요!
52f41af0a85bd5991059fe001a117824e1dab9e7

## 사양
OS 정보와 브라우저의 버전을 알려주세요!
windows 10, 네이버 웨일 (폰도 비슷함. 폰 : iPhone X, 네이버 웨일)

## 확인
- [O] 중복되는 이슈는 없나요?
- [O] 해당 버그를 다시 발생시킬 수 있나요?

**Comment by wonderlandpark** [comment]
버그가 아닙니다. 로그인으로 표시되는것은 캐시 데이터입니다. 로그인 세션이 만료되여, 토큰을 재발급할 필요가 있어, 보안상으로 재로그인 해야합니다.
