### ISSUE TITLE
[버그] API '/bots/@me' 에서 Owners데이터가 부분 누락되었습니다. 

### ISSUE THREAD

**Issue by ReDesignedJP** [koreanbots/koreanbots#25]
## 재현방법
Request

## 예상되는 정상적인 동작
잘나와야죠 

## 발생한 문제
제목

## 확인
- [ O ] 중복되는 이슈는 없나요?
- [ O ] 해당 버그를 다시 발생시킬 수 있나요?

**Comment by wonderlandpark** [comment]
고쳐드렸습니다. 다음부터는 성의있게 작성해주세요.
