### ISSUE TITLE
[버그] Safari 에서 심사에 있는 미리보기를 누른 후 뒤로가면 흰 페이지가 뜹니다.

### ISSUE THREAD

**Issue by Helloyunho** [koreanbots/koreanbots#27]
## 재현방법
1. Safari로 봇 사이트를 들어가 로그인 함
2. 로그인 후 프로필 페이지로 들어감
3. 봇 심사 이력에서 아무 봇이나 `미리 보기`를 클릭함
4. 봇 소개 페이지가 나올 때 뒤로 가기를 누름
5. 흰 페이지

## 예상되는 정상적인 동작
다시 프로필 페이지로 돌아가거나, 최소 다시 봇 소개로 리다이렉트 되어야 함.

## 발생한 문제
흰 페이지가 나옴.

## 클라이언트 버전
`[빌드 정보] 버전: 0.5.1 해시: 66071df3dde8ef1a69846cfe4577140a4b08a496`

## 사양
macOS 10.15.4 Catalina, Safari 13.1 (15609.1.20.111.8)
iPhone 11, iOS 13.3, Safari 버전 알 수 없음
iPhone 6s, iOS 13.3, Safari 버전 알 수 없음

## 확인
- [x] 중복되는 이슈는 없나요?
- [x] 해당 버그를 다시 발생시킬 수 있나요?

**Comment by wonderlandpark** [comment]
해당 브라우저는 공식적으로 지원하지 않습니다.
따라서 지금당장 고칠 예정은 없습니다.

**Comment by wonderlandpark** [comment]
또한 윤호씨의 iPhone은 JailBreak 된걸로 알고 있습니다. 따라서 해당 기기는 지원할 생각이 없습니다.

**Comment by hgl-215** [comment]
![1E6698EB-85BC-486B-AF60-012C3AC96699](https://user-images.githubusercontent.com/60605666/81298025-2608aa00-90af-11ea-8f55-d1447bfd7caf.gif)

현재 GIF는 아11 이긴 하나, 아7/아8 도 동일 증상이
나타나더군요

**Comment by Helloyunho** [comment]
iOS 13.5와 iPhone 11은 Jailbreak가 불가능한 상태입니다. 이 뜻은 Jailbreak 상태가 아니여도 버그가 일어난다고 볼 수 있겠네요. @wonderlandpark

**Comment by graybearr** [comment]
순정 아이폰XR 에서도 동일 증상 나타납니다.
![BB7E98AF-E2F4-45AE-A521-2623D48150A8](https://user-images.githubusercontent.com/48584233/81298382-aaf3c380-90af-11ea-995f-7388c5813f5a.png)

**Comment by Helloyunho** [comment]
그리고 iOS에서는 타 제조사 브라우저들도 WebKit을 쓰도록 되어있습니다. 그래서 iOS에선 타 브라우저로 회피한다고 해결되지 않을것 같습니다.

**Comment by hgl-215** [comment]
![84AA6BD4-9A01-4D12-B196-DAB0A6F76B79](https://user-images.githubusercontent.com/60605666/81299419-299d3080-90b1-11ea-969a-af56fb0b7110.gif)

현재 위 GIF 크롬브라우져 외 네이버도 테스트 해봤으나 모두 동일증상

**Comment by wonderlandpark** [comment]
Approved 되었습니다.

**Comment by wonderlandpark** [comment]
iOS/macOS 이외의 OS에서도 동일한 오류가 발생한다면 해당 이슈에 남겨주세요.

**Comment by wonderlandpark** [comment]
Apple 유저들에겐 심각한거 같아서 중요도를 올렸습니다.

**Comment by Helloyunho** [comment]
macOS Catalina 10.15.5, Safari 13.1.1 (15609.2.9.1.2)에서 다시 문제가 일어나고 있습니다.
