### ISSUE TITLE
[버그] 봇의 프로필 사진이 이상합니다.

### ISSUE THREAD

**Issue by samsunghappytree123** [koreanbots/koreanbots#29]
## 재현방법
어떻게하면 발생시킬 수 있나요?
> 기본 프사의 봇을 보시면 됩니다

## 예상되는 정상적인 동작
정상이라면 어떻게 되야하나요?
> 사진의 크기가 비슷하겠죠

## 발생한 문제
어떤 문제가 발생하나요?
> 그냥 기본 프사의 봇들은 프사 크기가 맞지 않습니다
> ![img](https://cdn.discordapp.com/attachments/707879035232845854/710125999635038224/Screenshot_2020-05-13_at_22.41.24.jpg)

## 클라이언트 버전
클라이언트 버전을 알려주세요!
> 49e733ffa969f3674a216ff0cfd1a504433aa0c4

## 사양
OS 정보와 브라우저의 버전을 알려주세요!
> Windows 10, 네이버 웨일

## 확인
- [ O ] 중복되는 이슈는 없나요?
- [ O ] 해당 버그를 다시 발생시킬 수 있나요?

**Comment by SaidBySolo** [comment]
CR Windows 1909 Google Chrome Version 81.0.4044.138 (Official Build) (64-bit)
![image](https://user-images.githubusercontent.com/33891531/81820794-04566980-956c-11ea-8656-8782974f6a70.png)

**Comment by wonderlandpark** [comment]
Apporved Will fix

**Comment by wonderlandpark** [comment]
Fixed

**Comment by 0xfmc** [comment]
구글이 좋습니다

**Comment by samsunghappytree123** [comment]
전 네이버 웨일이 좋습니다

개취니까 존중해요..

크로미움 브라우저는 같으니까

**Comment by SaidBySolo** [comment]
Extension in #77

#77 과 관련이있어 재오픈하였습니다.

**Comment by SaidBySolo** [comment]
``CR ``

Samsung Galaxy S7

Android 8.0.0

Build Version:1.1.0

![Screenshot_20200629-004204_Chrome](https://user-images.githubusercontent.com/33891531/85952027-a35ee580-b9a1-11ea-9569-8dbd598b2194.jpg)

**Comment by SaidBySolo** [comment]
1 Approve left

**Comment by tlfn** [comment]
![image](https://user-images.githubusercontent.com/53784981/85953376-c346d700-b9aa-11ea-8513-7071951f2a6b.jpeg)

아이폰X, XS, 11 Pro
iOS 13.5.1

**Comment by ReDesignedJP** [comment]
![image](https://user-images.githubusercontent.com/33867923/85956669-4e7f9700-b9c2-11ea-8f72-bb1129f9ee84.png)

크롬 모바일 에뮬레이터로 재현 가능합니다

**Comment by SaidBySolo** [comment]
More than two people can reproduce.
Approved this issue.

두명이상이 재현이 가능합니다
이문제는 승인되었습니다.
