### ISSUE TITLE
[버그] 가이드라인 오타

### ISSUE THREAD

**Issue by KaRinKaRin876** [koreanbots/koreanbots#32]
## 재현방법
봇 사이트에서 하단의 가이드라인 하이퍼링크 클릭

## 예상되는 정상적인 동작
글자(오타)가 제대로 수정되어 있어야 합니다.

## 발생한 문제
가이드라인의 일부 글자가 오타가 나있습니다.
![image](https://user-images.githubusercontent.com/64065435/81881658-b40ef400-95cb-11ea-8c08-9e3093ac97d2.png)

## 클라이언트 버전
[빌드 정보] 버전: 0.5.1 해시: bc15dcadf11b4e7146ed09fd59f0d0aa2817febd

## 사양
Microsoft Windows
버전 1903(OS 빌드 18362.657)

## 확인
- [x] 중복되는 이슈는 없나요?
- [x] 해당 버그를 다시 발생시킬 수 있나요?

**Comment by wonderlandpark** [comment]
Fixed
