### ISSUE TITLE
[버그] 봇 방송중일시 방송중이 안뜨는 버그

### ISSUE THREAD

**Issue by AIoneKR** [koreanbots/koreanbots#33]
## 재현방법
어떻게하면 발생시킬 수 있나요?
봇의 상태를 방송중으로 변경하면됨

## 예상되는 정상적인 동작
정상이라면 어떻게 되야하나요?
변경및 수정을 해야됩니다.

## 발생한 문제
어떤 문제가 발생하나요?
방송중인지 알수없습니다.

## 클라이언트 버전
클라이언트 버전을 알려주세요!
[빌드 정보] 버전: 0.7.0 해시: ebb8fd9a8b037c7f9d969c8f1244cdb87fbc97b9

## 사양
OS 정보와 브라우저의 버전을 알려주세요!
크롬
Microsoft Windows [Version 10.0.18363.778]

## 확인
- [ O ] 중복되는 이슈는 없나요?
- [ O ] 해당 버그를 다시 발생시킬 수 있나요?

**Comment by wonderlandpark** [comment]
Fixed
