### ISSUE TITLE
[버그] 카테고리 필터 적용 시 올바르게 정렬되지 않음

### ISSUE THREAD

**Issue by startbugs** [koreanbots/koreanbots#34]
## 재현방법
어떠한 카테고리든 클릭해서 적용시킵니다.
https://i.imgur.com/ro8rM5E.png

## 예상되는 정상적인 동작
봇들이 하트 순으로 정렬됩니다.

## 발생한 문제
하트 수에 상관없이 무작위로 정렬됩니다.

## 클라이언트 버전
0.7.0 

## 사양
Windows 10 Pro, Chrome

## 확인
- [x] 중복되는 이슈는 없나요?
- [x] 해당 버그를 다시 발생시킬 수 있나요?

**Comment by wonderlandpark** [comment]
Fixed
