### ISSUE TITLE
[버그] 화이트 모드에서 글자의 색이 반전되지 않음

### ISSUE THREAD

**Issue by startbugs** [koreanbots/koreanbots#35]
## 재현방법
화이트 모드를 활성화합니다.

## 예상되는 정상적인 동작
글자의 색상이 반전되어 드래그를 하지 않고도 나머지 태그가 몇 개 있는지 확인할 수 있어야 합니다.

## 발생한 문제
하양 글자가 반전되지 않아 화이트 모드에서 드래그를 하지 않고는 확인할 수 없습니다.
다크 => https://i.imgur.com/XgH6pGy.png
화이트 => https://i.imgur.com/yR4QDdv.png

## 클라이언트 버전
0.7.0

## 사양
Windows 10 Pro, Chrome

## 확인
- [x] 중복되는 이슈는 없나요?
- [x] 해당 버그를 다시 발생시킬 수 있나요?

**Comment by SaidBySolo** [comment]
Can Reproduce
Windows 1909
Google Chrome Version 81.0.4044.138 (Official Build) (64-bit)
[빌드정보] 버전: 0.7.0 해시: ebb8fd9a8b037c7f9d969c8f1244cdb87fbc97b9
