### ISSUE TITLE
[건의]봇을 추가할때 인증명령어를 만들었는지 표시하는 경고를 표시해주세요

### ISSUE THREAD

**Issue by SaidBySolo** [koreanbots/koreanbots#38]
최근들어 개발자 확인이 불가하는 일이많은거같습니다

등록하기전 팝업으로 경고표시를 한번 더띄웠으면 좋겠습니다.

**Comment by wonderlandpark** [comment]
프로세스중입니다

**Comment by wonderlandpark** [comment]
팝업은 아니지만 `SHAKE` 액션으로 구현했습니다.https://github.com/koreanbots/client/commit/9bf2b21fe06a090660688b47f49c518dca16d1a3
