### ISSUE TITLE
[버그] 제출 연타시 중복 등록 요청됨

### ISSUE THREAD

**Issue by khk4912** [koreanbots/koreanbots#39]
## 재현방법
[봇 추가하기](https://koreanbots.dev/addbot) 에서 제출 버튼 연타 시 두번 추가 요청 됨.
## 예상되는 정상적인 동작
정상이라면 어떻게 되야하나요?
한 번만 추가되어야함
## 발생한 문제
어떤 문제가 발생하나요?
두 번 추가됨
## 클라이언트 버전
클라이언트 버전을 알려주세요!
[빌드정보] 버전: 0.7.0 해시: 281e26f3500cf3bf4a2c3ef9630ff1fe5321ae85# 사양

## OS 정보와 브라우저의 버전을 알려주세요!
Windows 10 버전 2004 (빌드 19041.264)
Chrome 81.0.4044.138 (공식 빌드) (64비트) (cohort: Stable)

## 확인
- [y] 중복되는 이슈는 없나요?
- [y] 해당 버그를 다시 발생시킬 수 있나요?

**Comment by wonderlandpark** [comment]
Fixed
