### ISSUE TITLE
[버그] 화이트 모드로 변환 시 제공되는 카드가 가시성이 불명확함

### ISSUE THREAD

**Issue by MoartMedia** [koreanbots/koreanbots#42]
## 재현방법
어떻게하면 발생시킬 수 있나요?
다크 모드에서 화이트 모드로 변환.

## 예상되는 정상적인 동작
정상이라면 어떻게 되야하나요?
해당 카드는 다크 모드처럼 글꼴 색깔 유지하거나
회색 배경을 없에고 다른 색깔로 입혀야합니다. (하얀색이라던가)

## 발생한 문제
어떤 문제가 발생하나요?
화이트 모드로 변환하면 배경이 제공되는 카드 쪽이 가시성이 떨어집니다.

![image](https://user-images.githubusercontent.com/18746638/82308844-4fa1c980-99fd-11ea-91ce-6c3795565471.png)

## 클라이언트 버전
[빌드 정보] 버전: 0.7.0 해시: 2c1ad86cd491ccdf6c6329aed1cdb7e6a650f44d

## 사양
OS 정보와 브라우저의 버전을 알려주세요!
Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/80.0.3987.163 Whale/2.7.99.19 Safari/537.36
Microsoft Windows 10 Home 10.0.18362

## 확인
- [ V] 중복되는 이슈는 없나요?
- [ V] 해당 버그를 다시 발생시킬 수 있나요?

**Comment by wonderlandpark** [comment]
NAB, 버그가 아닙니다. 이미지 문제입니다. 버그보다는 제안에 가까운것 같군요, 새로운 이슈에서 부탁드립니다!
