### ISSUE TITLE
[버그] 인증된 봇 리스트가 잘리는 문제

### ISSUE THREAD

**Issue by GPM567** [koreanbots/koreanbots#43]
## 재현방법
어떻게하면 발생시킬 수 있나요?
메인페이지에서 스크롤을 가장 밑으로 내립니다.

## 예상되는 정상적인 동작
정상이라면 어떻게 되야하나요?
인증된 봇 리스트가 모두 보여야 합니다.

## 발생한 문제
어떤 문제가 발생하나요?
인증된 봇 리스트가 잘립니다.

## 클라이언트 버전
클라이언트 버전을 알려주세요!

버전: 0.7.0 해시: 14c3454bae67c4aace5f9a1437c4cb2e9fa73228

## 사양
OS 정보와 브라우저의 버전을 알려주세요!
Windows 10 버전 10.0.18363 빌드 18363
Chrome 버전 81.0.4044.138(공식 빌드) (64비트)

## 확인
- [O] 중복되는 이슈는 없나요?
- [O] 해당 버그를 다시 발생시킬 수 있나요?

**Comment by GPM567** [comment]
![image](https://user-images.githubusercontent.com/62422715/82336934-1fbaec00-9a26-11ea-8a05-b0088a052203.png)

**Comment by comjun04** [comment]
CR, LG G6 / Android 8.0 (Oreo), Chrome 81.0.4044.117
![Screenshot_2020-05-20-00-55-40](https://user-images.githubusercontent.com/30339539/82349237-d45c0a00-9a34-11ea-9057-bf6017a708cc.png)
