### ISSUE TITLE
[버그] Occurs when Method Not Allowed sends to http instead of https.

### ISSUE THREAD

**Issue by gunyu1019** [koreanbots/koreanbots#430]
## 재현방법
> 어떻게하면 발생시킬 수 있나요?

Postman 혹은 Method 값을 `Post`으로 보낼 수 있는 코드에서 https 프로토콜이 아닌 http 프로토콜로 API를 전송하면 발생합니다. Method를 GET으로 사용하는 일부 API가 해당된진 않지만 Method를 POST로 값을 전송해야 되는 `/bots/{bot.id}/stats`에서 해당 문제가 발생합니다.<br/>
![image](https://user-images.githubusercontent.com/16767890/122673869-915b0000-d20d-11eb-8e07-24349ca1e0d2.png)

## 예상되는 정상적인 동작
> 정상이라면 어떻게 되야하나요?

정상적인 동작이라면 Method를 POST 이든, GET이든 상관 없이 http에서도 API가 전송되어야만 합니다.<br/>
![image](https://user-images.githubusercontent.com/16767890/122674381-daac4f00-d20f-11eb-9300-440bd71407cf.png)

## 발생한 문제
> 어떤 문제가 발생하나요?

Koreanbots에 있는 API를 보낼 때 프로토콜를 https 대신, http로 보낼 경우 `Method Not Allowed(405)`가 발생합니다.
물론 이 현상은 Method를 POST로 보내야 하는 `/bots/{bot.id}/stats`만 한정됩니다.

## 클라이언트 버전
> 클라이언트 버전을 알려주세요!

Koreanbots API v2 입니다. 자세한 클라이언트 버전을 확인할 방법이 없네요 :(

## 사양
> OS 정보와 브라우저의 버전을 알려주세요!

**<컴퓨터 정보>**
CPU: AMD Ryzen 7 3800X 8-Core Processor 3.90 GHz
RAM: 32.0GB 2EA 3200Mhz(Overclocked)
GPU: NVIDIA RTX 2060 SUPER Founders Edtion

**<소프트웨어 정보>**
에디션:	Windows 10 Pro
버전:	20H2
설치 날짜:	‎2021-‎05-‎02
OS 빌드:	19042.1052

**<브라우저 정보>**
Postman for Windows Version 8.6.2 (win32 10.0.19042 / x64)

## 확인

- [x] 중복되는 이슈는 없나요?
- [x] 해당 버그를 다시 발생시킬 수 있나요?

<!--
마크다운 체크박스 문법입니다.
[x] - 체크
[ ] - 체크하지 않음
으로 작성해주세요.
>

**Comment by wonderlandpark** [comment]
http는 보안상의 문제로 지원하지 않을 예정입니다. https 프로토콜로 요청해주세요.

**Comment by gunyu1019** [comment]
제가 올린 이슈는 HTTP 프로토콜의 지원 문제가 아닙니다. HTTP 프로토콜에서 HTTPS 프로토콜로 변환하는 리다이렉트 과정에서 `GET`으로만  메소드가 고정된다는 점에서 이슈를 넣게 되었습니다. (위 본문에서 오인할만한 내용이 있어 보였습니다. 이점 죄송합니다.)

> 명세에서는 리다이렉트를 수행할 때 메소드(와 응답 본문)이 바뀌어서는 안 된다고 명시하고 있지만, 모든 유저 에이전트가 이를 따르는 것은 아니며 이러한 잘못된 소프트웨어는 아직도 찾아볼 수 있다. 그러므로 301 코드는 GET과 HEAD 메소드의 응답으로만 사용하고, POST 메소드에 대해서는 메소드 변경이 명시적으로 금지된 308 Permanent Redirect를 사용하는 것이 바람직하다.
(https://developer.mozilla.org/ko/docs/Web/HTTP/Status/301 일부 내용 인용)

`/bots/{bot.id}/stats` 를 사용하기 위해서는 POST 메소드를 사용해야 하며, 301(Moved Permanently)를 사용하는 것은 옳지 한다고 봅니다.

이 문제는 프로토콜을 올바르게 리다이렉트 하는 과정에서 301(Moved Permanently) 을 반환했기 때문에 `GET` 메소드로 고정되어 나갈 수 밖에 없습니다.

![image](https://user-images.githubusercontent.com/16767890/123064907-a7550480-d449-11eb-91a8-d7e838523667.png)
(API 전송과정 WireShark 패킷 수집 정보)

![image](https://user-images.githubusercontent.com/16767890/123066475-10894780-d44b-11eb-8dad-b58506442e93.png)
(API 전송과정 Postman 콘솔 정보)

따라서 308 (Permanent Redirect)으로 리다이렉트를 시도하면 정상적으로 해결할 수 있는 상황입니다.
HTTP -> HTTPS로 리다이렉트 하는 과정에서 301(Moved Permanently)가 아닌 308(Permanent Redirect)을 통하여 리다이렉트가 되도록 수정을 요청합니다.

**Comment by kms0219kms** [comment]
## 재현방법
> 어떻게하면 발생시킬 수 있나요?

> Postman 혹은 Method 값을 `Post`으로 보낼 수 있는 코드에서 https 프로토콜이 아닌 http 프로토콜로 API를 전송하면 발생합니다. Method를 GET으로 사용하는 일부 API가 해당된진 않지만 Method를 POST로 값을 전송해야 되는 `/bots/{bot.id}/stats`에서 해당 문제가 발생합니다.

![image](https://user-images.githubusercontent.com/16767890/122673869-915b0000-d20d-11eb-8e07-24349ca1e0d2.png)

## 예상되는 정상적인 동작
> 정상이라면 어떻게 되야하나요?

정상적인 동작이라면 Method를 POST 이든, GET이든 상관 없이 http에서도 API가 전송되어야만 합니다.

![image](https://user-images.githubusercontent.com/16767890/122674381-daac4f00-d20f-11eb-9300-440bd71407cf.png)

## 발생한 문제
> 어떤 문제가 발생하나요?

Koreanbots에 있는 API를 보낼 때 프로토콜를 https 대신, http로 보낼 경우 `Method Not Allowed(405)`가 발생합니다.
물론 이 현상은 Method를 POST로 보내야 하는 `/bots/{bot.id}/stats`만 한정됩니다.

## 클라이언트 버전
> 클라이언트 버전을 알려주세요!
 
Koreanbots API v2 입니다. 자세한 클라이언트 버전을 확인할 방법이 없네요 :(

## 사양
> OS 정보와 브라우저의 버전을 알려주세요!

**<컴퓨터 정보>**
CPU: 1.1 GHz 쿼드 코어 Intel Core i5
RAM: 32.0GB 2EA 3200Mhz(Overclocked)
GPU: Intel Iris Plus Graphics 1536 MB

**<소프트웨어 정보>**
에디션: macOS Big Sur
버전: 11.5
설치 날짜: ‎2021-‎06-‎20
OS 빌드: 20G5042c

**<브라우저 정보>**
Postman for macOS Version 8.6.2

## 확인
* [x]  중복되는 이슈는 없나요?
* [x]  해당 버그를 다시 발생시킬 수 있나요?

**Comment by kms0219kms** [comment]
macOS에서도 동일 증상이 발생하며, 프로토콜 변경은 HSTS 등의 시스템(자세히 아래에 적어 둘께요)으로 이동해야 올바르다고 봅니다.

**Comment by kms0219kms** [comment]
HSTS를 통해 Redirect를 할 경우 기본 응답 값이자,

프로토콜 리다이렉트시 가장 바람직하다고 평가되는 응답코드는 307 Internal Redirect 입니다.

307로의 수정을 요하는 바입니다.

**Comment by kms0219kms** [comment]
It's part of what's written on MDN.
"It is recommended to use the 301 response status code only as a response for GET or HEAD methods and to use the 308 Permanent Redirect for POST methods instead, as the method change is explicitly prohibited with this status."
And,
"The request method and the body will not be altered, whereas 301 may incorrectly sometimes be changed to a GET method."

**Comment by kms0219kms** [comment]
Link to MDN Document: https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/301
https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/308

**Comment by kms0219kms** [comment]
In addition, applying the security certificate to HTTPS from the beginning is not a bad way when requesting an API, but depending on the situation, installing the certificate may not be very good for the user experience.

**Comment by wonderlandpark** [comment]
위에서 언급한 것처럼 HTTP 프로토콜을 통한 API 요청을 지원할 경우 일부 유저 분들이 HTTP 프로코콜을 통한 요청을 전송하실 수 있습니다. 이는 패킷 탈취 등의 취약점으로 이어질 수 있어서 암호화된 HTTPS 프로토콜 사용을 강제하기 위해 HTTP 프로코콜에 대해서는 어떠한 지원도 하지 않을 예정입니다.
 
GET 메소드로 리다이렉트 되는 부분은 일반 사용자분들이 브라우저로 접속하는 경우 HTTP 프로코콜을 통한 접속 대신 HTTPS 프로코콜 사용을 강제 하기 위해서 이유입니다. 

해당 기술적인 부분은 대행사인 Cloudflare 사의 서비스를 이용하고 있습니다. SPEC에 맞지 않는 부분이 있다고 생각되시면 Cloudflare사의 지원 페이지를 참고해주세요.
https://support.cloudflare.com

**Comment by kms0219kms** [comment]
@gunyu1019 Please check comment " https://github.com/koreanbots/koreanbots/issues/430#issuecomment-867644411 "

> 위에서 언급한 것처럼 HTTP 프로토콜을 통한 API 요청을 지원할 경우 일부 유저 분들이 HTTP 프로코콜을 통한 요청을 전송하실 수 있습니다. 이는 패킷 탈취 등의 취약점으로 이어질 수 있어서 암호화된 HTTPS 프로토콜 사용을 강제하기 위해 HTTP 프로코콜에 대해서는 어떠한 지원도 하지 않을 예정입니다.
> 
> GET 메소드로 리다이렉트 되는 부분은 일반 사용자분들이 브라우저로 접속하는 경우 HTTP 프로코콜을 통한 접속 대신 HTTPS 프로코콜 사용을 강제 하기 위해서 이유입니다.
> 
> 해당 기술적인 부분은 대행사인 Cloudflare 사의 서비스를 이용하고 있습니다. SPEC에 맞지 않는 부분이 있다고 생각되시면 Cloudflare사의 지원 페이지를 참고해주세요.
> https://support.cloudflare.com
