### ISSUE TITLE
[버그] 서버수가 0인 봇 페이지 미리보기 이미지 숫자 표시 오류

### ISSUE THREAD

**Issue by comjun04** [koreanbots/koreanbots#433]
## 재현방법
디스코드에서 한디리에 있는 봇들 중 서버수가 **없는**(N/A) 봇 페이지 url을 전송합니다.

![image](https://user-images.githubusercontent.com/30339539/123046292-e62d8f00-d436-11eb-8f7a-23f1a8f0c0ab.png)

## 예상되는 정상적인 동작
서버 수가 0이라고 떠야합니다

## 발생한 문제
`0천`이라고 뜹니다.

![image](https://user-images.githubusercontent.com/30339539/123046224-cd24de00-d436-11eb-89c7-fc6ff1fa526c.png)

## 클라이언트 버전
...을 확인할 방법이 보이지가 않습니다. 주석으로 달아놓은 페이지는 지워졌습니다.

## 사양
이 문제는 OS와 관련없이 디스코드상에서 미리보기 임베드를 통해 나타나는 오류입니다.

## 확인

- [x] 중복되는 이슈는 없나요?
- [x] 해당 버그를 다시 발생시킬 수 있나요?

<!--
마크다운 체크박스 문법입니다.
[x] - 체크
[ ] - 체크하지 않음
으로 작성해주세요.
>

**Comment by kms0219kms** [comment]
The client version is a combination of Command + Shift + C, which opens Devtools and is located on the console. If not, please refresh it with Command + R.

**Comment by kms0219kms** [comment]
클라이언트 버전은 Command + Shift + C의 조합으로 Devtools를 Open하고 콘솔에 있습니다. 없으면, Command + R로 새로고침 해보시기 바랍니다.

**Comment by comjun04** [comment]
> 클라이언트 버전은 Command + Shift + C의 조합으로 Devtools를 Open하고 콘솔에 있습니다. 없으면, Command + R로 새로고침 해보시기 바랍니다.

v2에서도 버전이 뜨나요?
저는 버전이 안떴습니다

**Comment by kms0219kms** [comment]
@comjun04 #435 issue check please

**Comment by kms0219kms** [comment]
I can't see the client version value either.
