### ISSUE TITLE
[버그] 타임아웃 에러 발생

### ISSUE THREAD

**Issue by khk4912** [koreanbots/koreanbots#44]
## 재현방법
https://api.koreanbots.dev/bots/category/ 엔드포인트에서 param 중 page를 음수로 요청

## 예상되는 정상적인 동작
HTTP 상태 코드 400 리턴 (다른 엔드포인트에선 400 날라옴)

## 발생한 문제
타임아웃 에러 

## 클라이언트 버전
[빌드정보] 버전: 0.7.0 해시: 14c3454bae67c4aace5f9a1437c4cb2e9fa73228

## 사양
Windows 10 버전 2004 (빌드 19041.264)
Chrome 81.0.4044.138 (공식 빌드) (64비트) (cohort: Stable)

## 확인
- [y] 중복되는 이슈는 없나요?
- [y] 해당 버그를 다시 발생시킬 수 있나요?

**Comment by wonderlandpark** [comment]
`/bots/search` 엔드포인트도 동일한 버그가 재현가능합니다.

**Comment by wonderlandpark** [comment]
수정되었습니다 😉
