### ISSUE TITLE
[버그] 서버 수가 반올림되어 단위가 바뀌면 숫자가 그대로 표시됨

### ISSUE THREAD

**Issue by frin0911** [koreanbots/koreanbots#449]
## 재현방법

서버 수가 995개 이상 또는 9995개 이상으로 반올림 하였을 때 표기 단위가 바뀔 때

## 예상되는 정상적인 동작

`1천 서버`로 표기되어야 함.

## 발생한 문제

봇 목록 페이지에서 서버 수가 995개 이상이라면 반올림이 되어 봇 목록 페이지에서 `1000 서버`로 표시됨.

## 사양

OS 및 브라우저와 관련 없이 발생하는 문제이기에 생략함.

## 확인

- [x] 중복되는 이슈는 없나요?
- [x] 해당 버그를 다시 발생시킬 수 있나요?

**Comment by wonderlandpark** [comment]
재현 가능한 봇 아이디 하나 말씀해주실 수 있나요?

**Comment by frin0911** [comment]
한 3~4일 전까지는 `790968269007880232` 여기서 표시됐었는데, 지금은 1000서버 넘겨서 재현 불가능합니다.
