### ISSUE TITLE
[제안] 화이트모드시 미리보기 배경을 사용하는 봇의 텍스트 invert 필요

### ISSUE THREAD

**Issue by kijk2869** [koreanbots/koreanbots#45]
화이트모드시, 미리보기 배경이 어두워지는 관계로 글의 가독성이 떨어짐.

미리보기 배경을 사용하는 봇만 텍스트 invert가 필요해보임

비교샷
![적용전](https://user-images.githubusercontent.com/35522821/82392680-73a5ef00-9a7f-11ea-8eeb-a74f9c9dcae4.png)
![적용후](https://user-images.githubusercontent.com/35522821/82392619-507b3f80-9a7f-11ea-80ce-2a3b54ab966b.png)

**Comment by kijk2869** [comment]
#42 과 연결됨

**Comment by wonderlandpark** [comment]
Added it at https://github.com/koreanbots/client/commit/4d1292b39364fb8db6047f7e9820263146cc25a1
