### ISSUE TITLE
[건의]api문서의 사이드바 카테고리의 글씨의 크기를 늘려주세요

### ISSUE THREAD

**Issue by SaidBySolo** [koreanbots/koreanbots#49]
해상도가 높은 기기가 아닌데도 불구하고 글씨가 작습니다. (1366x768)

글씨의 크기를 늘려주시면좋겠습니다.

**Comment by wonderlandpark** [comment]
Added in https://github.com/koreanbots/client/commit/515e4a462b44b3985ef9e886e7c7ebcea5150428
