### ISSUE TITLE
깃허브,봇 초대하기링크는 다른링크로 대체되어서는 안됩니다.

### ISSUE THREAD

**Issue by SaidBySolo** [koreanbots/koreanbots#5]
## 재현 방법

[해당 링크](https://koreanbots.cf/addbot)에 들어가 봇을 추가 할때 github및 초대하기링크를 다른 URL로 써넣고 제출 하세요

## 예상되는 정상적인 동작

깃허브와 초대하기링크가 다른 url로 대체되면 안됩니다.

## 발생한 문제

[링크](https://koreanbots.cf/pendingBots/011918171615141312/1588358260)를 보면 깃허브와 초대하기링크가 다른 url로 대체됩니다.

## 사양

크롬 버전 81.0.4044.129(공식 빌드) (64비트)

**Comment by wonderlandpark** [comment]
버그가 아닙니다.

- 초대하기 링크는 봇 자체 초대링크가 있을 수 있기 때문에 만들어둔 칸입니다. (예) [원더봇 초대링크](https://wonderbot.xyz/invite)
- 또한, 깃은 깃허브만 존재하는 것이 아닙니다.
