### ISSUE TITLE
[제안] 화이트모드로 변경할시 커스텀으로 설정한봇의 배경이 너무 어둡습니다.

### ISSUE THREAD

**Issue by SaidBySolo** [koreanbots/koreanbots#50]
![image](https://user-images.githubusercontent.com/33891531/82538649-067d8100-9b87-11ea-97fe-75a34ce5caaf.png)

사진과같이 너무 어두운거같습니다.

해당부분을 화이트모드일때는 밝게해주셨으면 좋겠습니다.

**Comment by kijk2869** [comment]
반대, 배경을 밝게 하면(원본을 유지하면) 글의 가독성이 매우 떨어집니다.

**Comment by wonderlandpark** [comment]
![image](https://user-images.githubusercontent.com/31924512/82554720-6ed95c00-9ba1-11ea-89d0-797562ea2325.png)
배경문제
