### ISSUE TITLE
[제안] 봇 설명 패이지 배경사진 잘림현상

### ISSUE THREAD

**Issue by comjun04** [koreanbots/koreanbots#55]
## 재현방법
배경사진이 적용되어 있는 봇 설명 패이지로 들어갑니다.

## 예상되는 정상적인 동작
배경사진이 고루 나와야합니다.

## 발생한 문제
다음과 같이 잘리는 부분이 발생합니다.
![Capture+_2020-05-23-13-19-44](https://user-images.githubusercontent.com/30339539/82721489-634c7900-9cf8-11ea-8897-a7729a41f324.png)

![Capture+_2020-05-23-13-22-32](https://user-images.githubusercontent.com/30339539/82721502-80814780-9cf8-11ea-9a34-69657c598a23.png)

## 클라이언트 버전
v0.9.0 `8da2c8f`

## 사양
Android 8.0 (Oreo)
Chrome 81

## 확인
- [x] 중복되는 이슈는 없나요?
- [x] 해당 버그를 다시 발생시킬 수 있나요?

**Comment by wonderlandpark** [comment]
버그는 아니지만 제안사항으로 넘기겠습니다

**Comment by wonderlandpark** [comment]
아직 안고쳐진 부분이 있습니다.
