### ISSUE TITLE
[버그] 프로필의 '하트를 남긴 봇' 에서 봇 설명에 배경사진 적용되지 않음

### ISSUE THREAD

**Issue by comjun04** [koreanbots/koreanbots#57]
## 재현방법
* 배경사진 적용된 봇 설명 페이지에서 하트를 누릅니다.
* 내 프로필 페이지로 이동합니다.
* '하트를 남긴 봇'에서 해당 봇 설명란으로 이동합니다.

## 예상되는 정상적인 동작
해당 설명란에도 배경사진이 적용되어야 합니다.

## 발생한 문제
적용되지 않습니다.
* 메인페이지
![Screenshot_2020-05-23-13-28-32](https://user-images.githubusercontent.com/30339539/82721662-54ff5c80-9cfa-11ea-9ca1-b9ed98197458.png)

* 프로필 페이지
![Screenshot_2020-05-23-13-28-19](https://user-images.githubusercontent.com/30339539/82721668-66486900-9cfa-11ea-9244-5e6c314c5493.png)

## 클라이언트 버전
v0.9.0 `8da2c8f`

## 사양
Android 8.0 (Oreo)
Chrome 81

## 확인
- [x] 중복되는 이슈는 없나요?
- [x] 해당 버그를 다시 발생시킬 수 있나요?

**Comment by wonderlandpark** [comment]
신뢰된 봇 한정
