### ISSUE TITLE
[버그] 봇을 검색할 때 창 제목이 `가이드라인` 으로 설정되는 오류

### ISSUE THREAD

**Issue by samsunghappytree123** [koreanbots/koreanbots#58]
## 재현방법
어떻게하면 발생시킬 수 있나요?
> 봇 검색하기

## 예상되는 정상적인 동작
정상이라면 어떻게 되야하나요?
> 창 제목이 `검색결과` 등 적어도 `가이드라인` 은 나오지 않을 것 같네요

## 발생한 문제
어떤 문제가 발생하나요?
> 창 제목이 `가이드라인 - 한국 디스코드 봇 리스트` 로 바뀝니다.

## 클라이언트 버전
클라이언트 버전을 알려주세요!
8da2c8f46fa8a42c7d854244285ce627f8ef165c

## 사양
OS 정보와 브라우저의 버전을 알려주세요!
windows 10, 네이버 웨일 브라우저

## 확인
- [ Y ] 중복되는 이슈는 없나요?
- [ Y ] 해당 버그를 다시 발생시킬 수 있나요?

**Comment by comjun04** [comment]
CR, Android 8.0 (Oreo), Chrome 81
![Capture+_2020-05-23-14-58-43](https://user-images.githubusercontent.com/30339539/82722960-fb049400-9d05-11ea-81f0-b4ef03a79feb.png)
