### ISSUE TITLE
[버그] 

### ISSUE THREAD

**Issue by Jiseong0216** [koreanbots/koreanbots#59]
## 재현방법
알림이를 통해

## 예상되는 정상적인 동작
봇 서버수 업데이트가 되었나고 나와야 합니다.

## 발생한 문제
위 내용처럼 봇 서버수 업데이트가 안나옵니다. (Clover 봇 703861016613879815)

## 클라이언트 버전
클라이언트 버전을 알려주세요!
[빌드정보] 버전: 0.9.0 해시: 639c885677ddce7a604c8de4368fb47eee3df2d2

## 사양
Windows 10, 73.0.3683.103

## 확인
- [O] 중복되는 이슈는 없나요?
- [O] 해당 버그를 다시 발생시킬 수 있나요?

**Comment by MoartMedia** [comment]
서버 수 업데이트 관련이라면 해당 공식 디스코드 자주 물어 보는 질문 채널을 참고하세요.
 https://discordapp.com/channels/653083797763522580/706690936129847337/712165758452629586

이걸 정상적으로 넘겨지고 표시가 안뜨는 경우라면 자세히 이야기하셔야할 거 같은데요. 
지금 이슈 제보 내용이 너무 추상적입니다. 알림이는 무엇이며
봇 서버 수 되었냐고 물어보는 화면은 저는 본적이 없는 거 같습니다.
아마 comment나 이슈를 새로 여셔셔 다시 작성해야할 거 같네요.

**Comment by wonderlandpark** [comment]
No more action.
