### ISSUE TITLE
마크다운의 리스트와 인용구문이 제대로 표시되지않습니다.

### ISSUE THREAD

**Issue by SaidBySolo** [koreanbots/koreanbots#6]
## 재현방법

[해당 링크](https://koreanbots.cf/addbot)에 들어가 봇을 추가 할때 설명에 
```md
> 테스트 구문

* 테스트 구문

  * 테스트 구문

* 테스트 구문
```
해당 구문을 복사해서 붙여넣으세요

## 예상되는 정상적인 동작

![이미지1](https://i.imgur.com/CF3fTC9.jpg)
사진처럼 적용되어야합니다.

## 발생한 문제

![이미지2](https://i.imgur.com/cnZfEsV.jpg)
사진처럼 적용됩니다.

## 사양

크롬 버전 81.0.4044.129(공식 빌드) (64비트)

**Comment by wonderlandpark** [comment]
스타일 문제
고치는게 보기 좋을듯합니다.

**Comment by wonderlandpark** [comment]
구현하지 않도록 하겠습니다.
