### ISSUE TITLE
[버그] 내 프로필에서 " 신뢰된 봇 " 마크가 안뜹니다.

### ISSUE THREAD

**Issue by hgl-215** [koreanbots/koreanbots#60]
## 재현방법
어떻게하면 발생시킬 수 있나요?
> 내 프로필

## 예상되는 정상적인 동작
정상이라면 어떻게 되야하나요?
> 초록색으로 된 " 신뢰된 봇 " 마크가 떠야합니다.

## 발생한 문제
어떤 문제가 발생하나요?
> 문제가 발생하지는 않습니다.

## 클라이언트 버전
클라이언트 버전을 알려주세요!
> [빌드정보] 버전: 0.9.0 해시: 639c885677ddce7a604c8de4368fb47eee3df2d2

## 사양
OS 정보와 브라우저의 버전을 알려주세요!
> Windows 10 Home
> Chrome v81.0.4044.138

## 확인
- [x] 중복되는 이슈는 없나요?
- [x] 해당 버그를 다시 발생시킬 수 있나요?

![image](https://user-images.githubusercontent.com/60605666/82864207-056d9a80-9f5f-11ea-9364-ae24691a4b3b.png)

![image](https://user-images.githubusercontent.com/60605666/82864221-0acae500-9f5f-11ea-897e-0cfbe4ecbeec.png)

**Comment by comjun04** [comment]
CNR, Android 8.0 (Oreo), Chrome 81
저는 보입니다
![Screenshot_2020-05-26-14-44-17](https://user-images.githubusercontent.com/30339539/82864474-947ab280-9f5f-11ea-8cf0-be715bb2b6c2.png)
![Screenshot_2020-05-26-14-44-21](https://user-images.githubusercontent.com/30339539/82864485-98a6d000-9f5f-11ea-953c-205d2329711b.png)

**Comment by wonderlandpark** [comment]
@comjun04 하트를 남긴 봇이라고 작성하셨습니다.

**Comment by comjun04** [comment]
아까 댓글 삭제: 메인화면에서 찍었네요;;

**Comment by comjun04** [comment]
CR, Android 8.0(Oreo), Chrome 81
(아까 제대로 확인을 못했습니다.)
![Screenshot_2020-05-26-14-47-44](https://user-images.githubusercontent.com/30339539/82864617-e15e8900-9f5f-11ea-9b8a-be380082d899.png)
