### ISSUE TITLE
[건의] 버튼 추가

### ISSUE THREAD

**Issue by samsunghappytree123** [koreanbots/koreanbots#62]
봇의 상세정보를 확인하는 곳에 자신이 봇 제작 & 개발에 있는 사람들에게는 `봇 관리하기` 버튼을 추가해주셨으면 좋겠습니다.
봇을 관리하려면 프로필에서 봇 관리하기로 돌아가야 해서 힘들 때도 있다고 생각합니다.

**Comment by wonderlandpark** [comment]
Still needs approved

**Comment by zero734kr** [comment]
> Still needs approved

Still needs aproval

**Comment by wonderlandpark** [comment]
No action
