### ISSUE TITLE
[버그] 사이트가 CSRF 공격에 취약합니다

### ISSUE THREAD

**Issue by zero734kr** [koreanbots/koreanbots#64]
## 재현방법
[로그아웃 페이지](https://koreanbots.dev/logout)에 GET 요청 보내기

## 예상되는 정상적인 동작
타 서비스에 의하여 로그아웃 되는 일이 없어야 합니다

## 발생한 문제
그저 아무 방법이나, 아무 종류라도 [로그아웃 페이지](https://koreanbots.dev/logout)에 GET 요청을 보내면 유저가 모르는 새에 자동으로 로그아웃됩니다

## 클라이언트 버전
[빌드 정보] 버전: 0.9.9

## 사양

- **OS:** Linux Mint 19.3 Tricia
- **크롬 버전:** Google Chrome 81.0.4044.138

## 확인
- [x] 중복되는 이슈는 없나요?
- [x] 해당 버그를 다시 발생시킬 수 있나요?

**Comment by wonderlandpark** [comment]
인지하고 있긴합니다만, 중요한 정보를 수정하는건 아니라 그렇게 취약하지는 않지만, 로그인이 풀려버릴 수 있기에 수정하도록 하겠습니다.
