### ISSUE TITLE
[버그] 멘트가 다릅니다.

### ISSUE THREAD

**Issue by samsunghappytree123** [koreanbots/koreanbots#65]
## 재현방법
어떻게하면 발생시킬 수 있나요?
+ 어떤 페이지에서는 "관리 패널" 이라고 뜨지만 어떤 페이지에서는 "프로필" 이라고 뜹니다.
![img](https://cdn.discordapp.com/attachments/718355003177435229/721288296596111410/Screenshot_2020-06-13_at_17.59.59.jpg)
![img](https://cdn.discordapp.com/attachments/718355003177435229/721288301767819285/Screenshot_2020-06-13_at_18.00.51.jpg)

## 예상되는 정상적인 동작
정상이라면 어떻게 되야하나요?
+ 같은 멘트로 나와야 할것입니다.

## 발생한 문제
어떤 문제가 발생하나요?
+ 멘트가 다릅니다.

## 클라이언트 버전
클라이언트 버전을 알려주세요!

+ 64fcef5dea4d0d9fa12f4a0eb0b05cadbe1f0f1c
## 사양
OS 정보와 브라우저의 버전을 알려주세요!
Windows 10, Whale

## 확인
- [x] 중복되는 이슈는 없나요?
- [x] 해당 버그를 다시 발생시킬 수 있나요?

**Comment by wonderlandpark** [comment]
정보가 부족합니다. 정확히 어떤 페이지에서 그러는지 알려주세요. (그리고 저는 CNR)

**Comment by samsunghappytree123** [comment]
봇 관리 페이지 [이런거](https://koreanbots.dev/profile) 에는 2번째 사진처럼, [유저 페이지](https://koreanbots.dev/users/706355688707981363)에는 1번째처럼 바뀝니다.

**Comment by wonderlandpark** [comment]
캐시 문제인듯합니다. 재현할 수 없습니다.

**Comment by wonderlandpark** [comment]
그래도 동일한 문제가 발생할 수도 있으니 일단 Reopen 하겠습니다.

**Comment by SaidBySolo** [comment]
CNR 
Client ver:39e5d335cc4752fff29dedee1494296fbb165464

**Comment by wonderlandpark** [comment]
계속 재현하실 수 있으시다면, 새로운 이슈를 생성해주시거나 이 이슈에 Comment를 남겨주세요.
