### ISSUE TITLE
[버그] 페이지가 잘려서 보이는 문제

### ISSUE THREAD

**Issue by frin0911** [koreanbots/koreanbots#66]
## 재현방법
페이지 접속 후 최하단으로 스크롤

## 예상되는 정상적인 동작
잘리지 않고 body와 footer가 자연스럽게 보여야 함.

## 발생한 문제
페이지 최하단의 요소가 잘려서 보임.

## 클라이언트 버전
1.1.0

## 사양
Windows 10, 네이버 웨일 Version 2.7.99.22 (64-bit)

## 확인
- [x] 중복되는 이슈는 없나요?
- [x] 해당 버그를 다시 발생시킬 수 있나요?

**Comment by wonderlandpark** [comment]
화면 해상도를 알려주실 수 있나요? 저는 잘 보이네요

**Comment by frin0911** [comment]
1920 x 1080인데 레이아웃 배율이 125%입니다. (권장이 125%)
아마 레이아웃 확대 시 문제인 것 같습니다.

**Comment by wonderlandpark** [comment]
`CNR`
![image](https://user-images.githubusercontent.com/31924512/84565040-75728200-ada1-11ea-92a8-96f8f9f72f1d.png)

**Comment by SaidBySolo** [comment]
CNR
![image](https://user-images.githubusercontent.com/33891531/84581571-882a9c80-ae1d-11ea-8de7-9fba0cbd25e7.png)

**Comment by wonderlandpark** [comment]
Denied
