### ISSUE TITLE
[버그] 토큰이 보여지는 상태로 복사가 안 됩니다

### ISSUE THREAD

**Issue by zero734kr** [koreanbots/koreanbots#69]
## 재현방법
봇 관리 페이지에서 토큰 부분에 `보이기`를 클릭한 후 `복사하기` 클릭

## 예상되는 정상적인 동작
해당 봇의 토큰 복사

## 발생한 문제
토큰이 보여지는 상태에서 복사하기를 클릭하면 복사가 되지 않습니다.

## 클라이언트 버전
1.1.0

## 사양
OS: Linux Mint 19.3 Tricia
Chrome: Google Chrome 83.0.4103.97

## 확인
- [x] 중복되는 이슈는 없나요?
- [x] 해당 버그를 다시 발생시킬 수 있나요?
- [x] 때대로 발생함

**Comment by sus5373** [comment]
되는데요?

**Comment by zero734kr** [comment]
@sus5373 안 되는 경우가 있으니까 이슈를 생성한거겠죠?

**Comment by wonderlandpark** [comment]
alert 확인을 눌러야 복사가 됩니다.

**Comment by wonderlandpark** [comment]
또 버그는 재현 순서를 시행하면 무조건 발생해야합니다.

**Comment by wonderlandpark** [comment]
재현이 불가능합니다.
