### ISSUE TITLE
[버그] 모바일에서 메뉴 배경이 나오지 않음

### ISSUE THREAD

**Issue by kimcoreovo** [koreanbots/koreanbots#70]
## 재현방법
어떻게하면 발생시킬 수 있나요?
- 모바일 브라우저에서 메뉴 버튼 클릭
## 예상되는 정상적인 동작
정상이라면 어떻게 되야하나요?
- 메뉴의 배경이 제대로 표시
## 발생한 문제
어떤 문제가 발생하나요?
![image](https://user-images.githubusercontent.com/36142378/85203588-c6f2b200-b349-11ea-8cb9-e4219ec2cd5c.png)
- 메뉴의 배경이 투명하고 글자만 나옴
## 클라이언트 버전
클라이언트 버전을 알려주세요!
- iPhone 11
- 버전: 1.1.0
- 해시: ca3087c039797e6aeb11535b4c5c430077fb4b7e

## 사양
OS 정보와 브라우저의 버전을 알려주세요!
- iOS 13.5.1 / Chrome (WebKit)
## 확인
- [x] 중복되는 이슈는 없나요?
- [x] 해당 버그를 다시 발생시킬 수 있나요?

**Comment by wonderlandpark** [comment]
클라이언트 버전을 작성해주시면 좋겠습니다.

**Comment by wonderlandpark** [comment]
`CNR` LG Q9 
버전: 1.1.0 해시: ca3087c039797e6aeb11535b4c5c430077fb4b7e

**Comment by kimcoreovo** [comment]
수정했습니다.

**Comment by turtle85917** [comment]
ASFS
