### ISSUE TITLE
[건의] 봇 삭제기능을 페이지에 넣어주세요

### ISSUE THREAD

**Issue by sus5373** [koreanbots/koreanbots#72]
디스코드 문의 채널에서 계속 삭제해달라고 하니 불편하네요. 삭제버튼이 있으면 좋겠습니다.

**Comment by kiki7000** [comment]
있던데요

**Comment by kiki7000** [comment]
봇 관리하기 들어가고 맨 아래로 가면 되요

**Comment by sus5373** [comment]
@kijk2869 옼 있었네요 감사합니다

**Comment by sus5373** [comment]
@kijk2869 
![image](https://user-images.githubusercontent.com/61257727/85827077-71daf400-b7c0-11ea-8841-223162cbdd0f.png)
...???????

**Comment by kiki7000** [comment]
엌
전 그리고 @kiki7000

**Comment by kiki7000** [comment]
그냥 잠금해주세요

**Comment by wonderlandpark** [comment]
실수로 닫은듯 합니다

**Comment by SaidBySolo** [comment]
Need Approve

@koreanbots

**Comment by SaidBySolo** [comment]
Approved
