### ISSUE TITLE
[건의] 새로 추가된 봇 칸을 만들어주세요! 

### ISSUE THREAD

**Issue by minibox724** [koreanbots/koreanbots#73]
하트 랭킹, 신뢰된 봇 뒤에 새로 추가된 봇 칸을 만들어주세요
> 서버 수 정렬이 아닌 유용한 봇에 유저가 주는 하트 개념으로, 유용한 봇을 쉽고 빠르게 찾을 수 있으며, **소규모봇도 홍보효과를 볼 수 있다.** - 나무위키

에 따라서 소규모봇도 잠시나마 홍보 효과를 볼수 있게 새로 추가된 봇 칸이 있으면 좋겠네요

**Comment by wonderlandpark** [comment]
Developer Approved

**Comment by wonderlandpark** [comment]
Added at https://github.com/koreanbots/client/commit/416416a86412fe19355046f432bac5dc66012355
