### ISSUE TITLE
[버그] 잘못된 URL을 전송해도 수정 성공이 나타남

### ISSUE THREAD

**Issue by khk4912** [koreanbots/koreanbots#74]
## 재현방법
`봇 관리하기` 에서 웹사이트 / 깃 에 올바르지 않은 URL 입력

## 예상되는 정상적인 동작
변경이 반영되지 않으므로 적어도 오류 메시지가 발생해야함

## 발생한 문제
![chrome_J2RyqwpTYB](https://user-images.githubusercontent.com/30457148/85926867-531e4f80-b8dd-11ea-96a8-08c514ed4980.png)
정보 수정 성공이 뜸

## 클라이언트 버전
[빌드 정보] 버전: 1.1.0 해시: 0351b0bedc7c0b1ca8486468bf7aa23cc54ea003

## 사양
Windows 10 버전 20H2 (OS 빌드 19042.330)
Chrome 83.0.4103.116 (공식 빌드) (64비트) (cohort: Stable) 

## 확인
- [x] 중복되는 이슈는 없나요?
- [x] 해당 버그를 다시 발생시킬 수 있나요?

**Comment by wonderlandpark** [comment]
`CNR` ![image](https://user-images.githubusercontent.com/31924512/85946340-c5933c00-b97e-11ea-8ddc-18f5170a3d6e.png)
클라이언트 사이드에서 핸들하진 않지만 크롬에서 핸들해주는듯 합니다.

**Comment by SaidBySolo** [comment]
CNR

Samsung galaxy S7

버전:1.1.0

![Screenshot_20200628-234219_Chrome](https://user-images.githubusercontent.com/33891531/85950674-216abe80-b999-11ea-98c7-0a9e4414ee15.jpg)

In Chrome

**Comment by SaidBySolo** [comment]
Unfortunately, this issue was rejected because it was not reproduced.
붛행히도 이 이슈는 재현되지않아 거부되었습니다.

**Comment by khk4912** [comment]
이슈 내용을 잘못 이해하신 것 같습니다. 추후 사진 첨가로 다시 Comment 달겠습니다.

**Comment by khk4912** [comment]
![chrome_sCZCBPODqd](https://user-images.githubusercontent.com/30457148/86008438-b92ce300-ba53-11ea-8c81-e2e4f317566c.png)
정보 업데이트 시 위 사진처럼 실제로 접속이 불가능한 사이트를 넣고 저장하면,  

![chrome_btE18Pe5rt](https://user-images.githubusercontent.com/30457148/86008500-db266580-ba53-11ea-901f-51ce2964df70.png)
성공했다고 뜨지만 실제 봇 프로필에는 반영되지 않습니다.

**Comment by wonderlandpark** [comment]
Developer Approved

**Comment by wonderlandpark** [comment]
Too Minor will fix someday
