### ISSUE TITLE
[버그] 소개 페이지에서 .png.글자가 보임

### ISSUE THREAD

**Issue by kiki7000** [koreanbots/koreanbots#75]
## 재현방법
소개 페이지에 들어간다

## 예상되는 정상적인 동작
아이콘만 보이거나 .png 글자 대신 다운로드라는 글자가 보인다

## 발생한 문제
.png라는 텍스트가 보이고 누르면 사진이 다운로드됩니다

## 클라이언트 버전
0351b0bedc7c0b1ca8486468bf7aa23cc54ea003

## 사양
샤오미 홍미노트 4

## 확인
- [x] 중복되는 이슈는 없나요? O
- [x] 해당 버그를 다시 발생시킬 수 있나요? O

**Comment by SaidBySolo** [comment]
버그가 아닙니다. 의도한것입니다.
