### ISSUE TITLE
[제안] 화이트 모드에서 koreanbots api 페이지의 api 목차를 흰색으로 해주세요

### ISSUE THREAD

**Issue by mua1048** [koreanbots/koreanbots#76]
## 기능 설명
> koreanbots api 페이지 목차

## 필요한 이유
> 화이트 모드에 맞게 api 페이지 목차를 화이트로 변경해 주셨으면 합니다.

## 기대 효과
> 화이트 모드에 알맞은 목차를 사용할 수 있습니다.

## 확인
- [x] 중복되는 제안사항은 없나요?
- [x] 현실성 있는 제안인가요?

**Comment by SaidBySolo** [comment]
이슈템플릿양식에 맞춰서 작성해주세요.

변경사항없을시 클로즈하겠습니다.

**Comment by wonderlandpark** [comment]
![image](https://user-images.githubusercontent.com/31924512/85950974-f84b2d80-b99a-11ea-9498-f82ce69cb8ac.png)

**Comment by SaidBySolo** [comment]
Need Approve

@koreanbots

**Comment by wonderlandpark** [comment]
다크 유지할 생각입니다. 푸터와 색 통일하려고 한 결정입니다.
