### ISSUE TITLE
[버그] 디스코드 기본 프로필 사진 사용 시 크기가 조금 크게 보입니다.

### ISSUE THREAD

**Issue by GPM567** [koreanbots/koreanbots#77]
## 재현방법
> 어떻게하면 발생시킬 수 있나요?

디스코드 기본 프로필 사진을 사용한 봇이 있는 페이지로 갑니다.

## 예상되는 정상적인 동작
> 정상이라면 어떻게 되야하나요?

조금 작게 보여야 합니다.

## 발생한 문제
> 어떤 문제가 발생하나요?

프로필 사진의 크기가 좀 크게 보이고,
그에 따라 밑의 소개란도 조금 내려가있습니다.
![image](https://user-images.githubusercontent.com/62422715/85951178-5c222600-b99c-11ea-975c-db7e62f56273.png)

## 클라이언트 버전
> 클라이언트 버전을 알려주세요!

버전 1.1.0

## 사양
> OS 정보와 브라우저의 버전을 알려주세요!

Windows 10 Pro 1909
Chrome 버전 83.0.4103.116(공식 빌드) (64비트)

## 확인
- [ ] 중복되는 이슈는 없나요?
- [x] 해당 버그를 다시 발생시킬 수 있나요?

<!--
마크다운 체크박스 문법입니다.
[x] - 체크
[ ] - 체크하지 않음
으로 작성해주세요.
>

**Comment by SaidBySolo** [comment]
Extension in #29

**Comment by SaidBySolo** [comment]
@GPM567 

Extension in #29
I will clode this issue
Reopen #29
Please leave comment in #29

#29 와 관련이있는듯 합니다.
현재 이슈는 닫도록 하겠습니다.
#29 를 재오픈 하겠습니다.
의견남겨주세요
