### ISSUE TITLE
[버그] 프로필 사진 깨짐

### ISSUE THREAD

**Issue by yangseunghyeon** [koreanbots/koreanbots#78]
## 재현방법
> Koreanbots 로그인후, 디스코드 아바타 변경할 경우

## 예상되는 정상적인 동작
> 아바타가 변경되어야합니다.

## 발생한 문제
> 우측 상단에 사진이 깨져서 나옵니다.

## 클라이언트 버전
> 912f79172807aa6a13998d381a210e8eab0f92c2

## 사양
> Windows 10, Naver Whale

## 확인
- [ O ] 중복되는 이슈는 없나요?
- [ O ] 해당 버그를 다시 발생시킬 수 있나요?

<!--
마크다운 체크박스 문법입니다.
[x] - 체크
[ ] - 체크하지 않음
으로 작성해주세요.
>

**Comment by wonderlandpark** [comment]
체크박스 양식 맞춰주세요.

**Comment by wonderlandpark** [comment]
재로그인 하면 해결됩니다.
