### ISSUE TITLE
[제안] GIF 프로필 재생 기능

### ISSUE THREAD

**Issue by kiki7000** [koreanbots/koreanbots#79]
## 기능 설명
> GIF 사진을 자동으로재생하기 해주세요

## 필요한 이유
> GIF의 첫사진만 담으면 안예뻐요

## 기대 효과
> GIF 프사가 움직여서 보기 예뻐져요

## 확인
- [x] 중복되는 제안사항은 없나요?
- [x] 현실성 있는 제안인가요?

<!--
마크다운 체크박스 문법입니다.
[x] - 체크
[ ] - 체크하지 않음
으로 작성해주세요.
>

**Comment by wonderlandpark** [comment]
구현할 생각이 없습니다. GIF 프로필 사진은 일부러 고정한것입니다.
