### ISSUE TITLE
로그인을 하고 다시 로그인 하는 URL로 접속할시 디스코드 인증 창이 다시뜹니다.

### ISSUE THREAD

**Issue by SaidBySolo** [koreanbots/koreanbots#8]
## 재현방법

[해당 링크](https://koreanbots.cf)에 들어가 로그인합니다.

<https://koreanbots.cf/login>해당 링크를 다시들어갑니다.

## 예상되는 정상적인 동작

디스코드 로그인창이 다시뜨면 안됩니다.

## 발생한 문제

디스코드 로그인창이 다시뜹니다.

## 사양

크롬 버전 81.0.4044.129(공식 빌드) (64비트)

**Comment by wonderlandpark** [comment]
버그가 아닙니다. 의도한 것입니다.
