### ISSUE TITLE
[버그] 봇은 온라인인데 사이트에는 오프라인으로 보임.

### ISSUE THREAD

**Issue by samsunghappytree123** [koreanbots/koreanbots#80]
## 재현방법
> 어떻게하면 발생시킬 수 있나요?
**일부 봇을 확인할 때는 봇이 켜져있지만 사이트에는 꺼져있다고 뜸**

## 예상되는 정상적인 동작
> 정상이라면 어떻게 되야하나요?
**봇이 켜져있음을 알림 (온라인, 자리비움, 다른 용무중, 방송중 등)**

## 발생한 문제
> 어떤 문제가 발생하나요?
**봇이 오프라인이라고 뜸**
![img](https://cdn.discordapp.com/attachments/726355010048229376/727055588692852797/unknown.png)

## 클라이언트 버전
> 클라이언트 버전을 알려주세요!

68cf9a6797f6ffbd8c25842a85390826d9dbe9ca
## 사양
> OS 정보와 브라우저의 버전을 알려주세요!
**windows 10 1909, Naver Whale

## 확인
- [x] 중복되는 이슈는 없나요?
- [x] 해당 버그를 다시 발생시킬 수 있나요?

<!--
마크다운 체크박스 문법입니다.
[x] - 체크
[ ] - 체크하지 않음
으로 작성해주세요.
>

**Comment by SaidBySolo** [comment]
NAB

하루정도 기다리신후 문제가 계속된다면 이슈를 열어주세요

**Comment by SaidBySolo** [comment]
https://discord.com/channels/653083797763522580/706152196944953486/726643286613164102

다시확인해보니 초대한지 하루가 지난것같네요

하지만 케이스가 아직 불명확합니다 조금더 지켜보아야한거같으니 다시 이슈를 열긴하겠습니다.

**Comment by wonderlandpark** [comment]
버그는 재현될 수 있어야합니다. 특정 기기 등이 아닌 특정 봇에서만 재현되는것은 버그가 아닙니다.
