### ISSUE TITLE
[버그] 하트갯수가 -1개가 됬어요!!

### ISSUE THREAD

**Issue by gunyu1019** [koreanbots/koreanbots#83]
## 재현방법
> 어떻게하면 발생시킬 수 있나요? 디스코드봇을 재등록하고, 승인나서 등록이 된다면, 하트를 누른 유저는 유지되나봐요... 하트가 0개인데 하트삭제버튼이라고 뜨네요.
![Screenshot_20200630-230438_Samsung Internet](https://user-images.githubusercontent.com/16767890/86136692-586eda80-bb27-11ea-9fc1-c8a5009a5435.jpg) [링크](
https://koreanbots.dev/bots/680694763036737536)

## 예상되는 정상적인 동작
> 정상이라면 어떻게 되야하나요? 하트가 리셋되여 하지않을까요?..(~~아니면 5개를 다시 채워주세요~~)

## 발생한 문제
> 어떤 문제가 발생하나요? 하트갯수가 -1개에요

## 클라이언트 버전
> 클라이언트 버전을 알려주세요! 버전: 1.1.0 해시: 173c6ca7e41f1df6dbd87d8725dc577ca0ad7fd8
 

## 사양
> OS 정보와 브라우저의 버전을 알려주세요! Android 8, 삼성 인터넷

## 확인
- [x] 중복되는 이슈는 없나요? 
- [x] 해당 버그를 다시 발생시킬 수 있나요?

<!--
마크다운 체크박스 문법입니다.
[x] - 체크
[ ] - 체크하지 않음
으로 작성해주세요.
>

**Comment by SaidBySolo** [comment]
재현이 어려운 문제입니다.
관리자의 검토가필요합니다. @koreanbots

**Comment by wonderlandpark** [comment]
버그입니다.

**Comment by wonderlandpark** [comment]
해결됨
