### ISSUE TITLE
[제안] 순위 검색

### ISSUE THREAD

**Issue by noryonkr** [koreanbots/koreanbots#84]
## 기능 설명
> 어떤 기능인가요?
순위검색기능
## 필요한 이유
> 해당 기능을 왜 추가해야하나요?
순위는 버튼을 자꾸봐야하기때문에 순위 검색기능이 있었으면 좋겠습니다.
## 기대 효과
> 해당 기능을 추가하면 어떤 이점이 발생하나요?
순위 검색가능합니다
## 확인
- [없음 ] 중복되는 제안사항은 없나요?
- [봇의 순위를 검색할수있으므로 현실성이있다고 봅니다 ] 현실성 있는 제안인가요?

<!--
마크다운 체크박스 문법입니다.
[x] - 체크
[ ] - 체크하지 않음
으로 작성해주세요.
>

**Comment by wonderlandpark** [comment]
체크박스 문법을 맞춰주세요.
