### ISSUE TITLE
[버그] 유저 페이지 오타

### ISSUE THREAD

**Issue by GPM567** [koreanbots/koreanbots#85]
## 재현방법
> 어떻게하면 발생시킬 수 있나요?

유저 페이지로 들어갑니다.

## 예상되는 정상적인 동작
> 정상이라면 어떻게 되야하나요?

문장에 오류가 없어야 합니다.

## 발생한 문제
> 어떤 문제가 발생하나요?

'해당 유저에 개발하였거나, 관리하는 봇입니다.'라고 표시됩니다.
'해당 유저가 개발에 참여하였거나, 관리하는 봇입니다.' 등의 문장으로 바꾸는 것이 나아 보입니다.
![image](https://user-images.githubusercontent.com/62422715/86333970-94b94c80-bc87-11ea-9760-3322208d3bc2.png)

## 클라이언트 버전
> 클라이언트 버전을 알려주세요!

버전 1.1,0

## 사양
> OS 정보와 브라우저의 버전을 알려주세요!
Windows 10 Pro 1909
Chrome 버전 83.0.4103.116(공식 빌드) (64비트)

## 확인
- [x] 중복되는 이슈는 없나요?
- [x] 해당 버그를 다시 발생시킬 수 있나요?

<!--
마크다운 체크박스 문법입니다.
[x] - 체크
[ ] - 체크하지 않음
으로 작성해주세요.
>

**Comment by SaidBySolo** [comment]
https://github.com/SaidBySolo/client/commit/9a2e32201b098bfc007e96d6ca7e7a4d88f1a357

will be can fixed this issue
