### ISSUE TITLE
[버그] 유저 프로필을 화이트모드 적용하면 봇의 순서가 바뀌어서나옴

### ISSUE THREAD

**Issue by SaidBySolo** [koreanbots/koreanbots#86]
## 재현방법
> 어떻게하면 발생시킬 수 있나요?

https://koreanbots.dev/users/345265069132742657 에 접속합니다

footer에 테마를변경합니다.

## 예상되는 정상적인 동작
> 정상이라면 어떻게 되야하나요?

![image](https://user-images.githubusercontent.com/33891531/86334507-40629c80-bc88-11ea-8634-ec24766ea574.png)

테마를 바뀌어도 다음과같이 나와야합니다.

## 발생한 문제
> 어떤 문제가 발생하나요?

![image](https://user-images.githubusercontent.com/33891531/86334545-4f494f00-bc88-11ea-8f06-ab699ad11d15.png)

순서가 바뀌어서나옵니다.

## 클라이언트 버전
> 클라이언트 버전을 알려주세요!

[빌드 정보] 버전: 1.1.0 해시: 173c6ca7e41f1df6dbd87d8725dc577ca0ad7fd8

## 사양
> OS 정보와 브라우저의 버전을 알려주세요!

Windows 10
Chrome 83

## 확인
- [x] 중복되는 이슈는 없나요?
- [x] 해당 버그를 다시 발생시킬 수 있나요?

<!--
마크다운 체크박스 문법입니다.
[x] - 체크
[ ] - 체크하지 않음
으로 작성해주세요.
>

**Comment by kiki7000** [comment]
랜덤이여서 그런거 아닌가요?

**Comment by kiki7000** [comment]
![image](https://user-images.githubusercontent.com/51841836/86334802-a51df700-bc88-11ea-94c0-c3cf7d6a75c3.png)
**랜덤**

**Comment by SaidBySolo** [comment]
@kiki7000 보통 랜덤이면 새로고침해야 바뀌지않을까요

**Comment by SaidBySolo** [comment]
Self close
