### ISSUE TITLE
[제안] api에 랭킹 추가

### ISSUE THREAD

**Issue by samsunghappytree123** [koreanbots/koreanbots#87]
## 기능 설명
> 어떤 기능인가요?
[koreanbots api](https://api.koreanbots.dev)에서 봇 페이지 ( 예 : https://api.koreanbots.dev/bots/get/726376311710548049 )에 하트 순위를 추가해주셨으면 합니다.

## 필요한 이유
> 해당 기능을 왜 추가해야하나요?
- 비효율적이게 페이지를 읽어와서 랭킹을 집게하지 않아도 됩니다.

## 기대 효과
> 해당 기능을 추가하면 어떤 이점이 발생하나요?
- 자신의 봇 랭킹을 확인하기 위해 페이지를 읽어오는 방법보다 효율적입니다.
- 랭킹을 더욱 쉽게 조회할 수 있습니다.
- 기존 1~9위만 나타내었는데 page2부터 (10위\~)는 조회를 하기 어려웠지만 쉬워질 것입니다.

## 확인
- [x] 중복되는 제안사항은 없나요?
- [x] 현실성 있는 제안인가요?

<!--
마크다운 체크박스 문법입니다.
[x] - 체크
[ ] - 체크하지 않음
으로 작성해주세요.
>

**Comment by wonderlandpark** [comment]
구현 예정없습니다. 봇 정보를 불러오며 순위를 한 번 더 조회하며 정렬하면 리소스 낭비가 생깁니다.
