### ISSUE TITLE
[제안] - Windows 7 이전의 OS 명칭 수정

### ISSUE THREAD

**Issue by thoratica** [koreanbots/koreanbots#89]
## 기능 설명
> 어떤 기능인가요?
```
- Windows 7 이전의 OS
```
에서 OS를 Windows로 바꿔주세요

## 필요한 이유
> 해당 기능을 왜 추가해야하나요?  
다른건 OS의 이름이 나와있는데, Windows만 OS로 나와있어서 보기 불편해요 ㅎ;;

## 기대 효과
> 해당 기능을 추가하면 어떤 이점이 발생하나요?  
편-안해져요

## 확인
- [x] 중복되는 제안사항은 없나요?
- [x] 현실성 있는 제안인가요?

<!--
마크다운 체크박스 문법입니다.
[x] - 체크
[ ] - 체크하지 않음
으로 작성해주세요.
>

**Comment by wonderlandpark** [comment]
이슈는 사이트 관련만 받습니다.
