### ISSUE TITLE
[버그] 

### ISSUE THREAD

**Issue by kiki7000** [koreanbots/koreanbots#91]
## 재현방법
> 봇 수정을 합니디

## 예상되는 정상적인 동작
> 봇 신청을 했을때처럼 무슨 메시지가 떠야합니다

## 발생한 문제
> 아래 사진처럼 링크에는 메시지를 표시하라 하지만 아무 메시지도 있지 않습니다
![image](https://user-images.githubusercontent.com/51841836/87891808-35747e00-ca76-11ea-9717-d360681aa8f5.png)

## 클라이언트 버전
> 4b45fd261da9a564f8f7022ccf8c909dfb5b4798

## 사양
> 파이어폭스 78.0.2 버전(64비트), 윈도우 10

## 확인
- [o] 중복되는 이슈는 없나요?
- [o] 해당 버그를 다시 발생시킬 수 있나요?

<!--
마크다운 체크박스 문법입니다.
[x] - 체크
[ ] - 체크하지 않음
으로 작성해주세요.
>

**Comment by samsunghappytree123** [comment]
배너 밑으로 이동된 것 같습니다.
![img](https://cdn.discordapp.com/attachments/734301217575927828/734587793119903814/unknown.png)

**Comment by kiki7000** [comment]
앜 제가 바보네요
