### ISSUE TITLE
위젯을 넣어주세요!

### ISSUE THREAD

**Issue by turtle85917** [koreanbots/koreanbots#92]
## 기능 설명
서버 위젯입니다. 위젯을 넣으면 서버 인원수나 봇 수를 볼 수 있습니다.
서버 위젯이란 다음과 같이 생겼습니다!
[![](https://cdn.discordapp.com/attachments/734363189088747521/736350583187046500/unknown.png)]()

## 필요한 이유
서버 위젯이 있어야 사람들이 서버에 어떤 사람이 있는 지 알 수 있을 것 같습니다.

## 기대 효과
서버 위젯을 보고 사람들이 신뢰하고 들어올 수 있을 것 같습니다!

## 위치
[![](https://cdn.discordapp.com/attachments/734363189088747521/736351019373428887/unknown.png)]()
(빨간색으로 되어 있는 곳에다가 넣어주시면 고맙겠습니다!)

## 확인
- [x] 중복되는 제안사항은 없나요?
- [x] 현실성 있는 제안인가요?

<!--
마크다운 체크박스 문법입니다.
[x] - 체크
[ ] - 체크하지 않음
으로 작성해주세요.
>

**Comment by wonderlandpark** [comment]
서버위젯이 뭐고 어디다가 추가해달라는건지 추가설명 부탁드립니다.

**Comment by wonderlandpark** [comment]
서버위젯이 뭐고 어디다가 추가해달라는건지 추가설명 부탁드립니다.

**Comment by turtle85917** [comment]
추가했습니다

**Comment by wonderlandpark** [comment]
서버위젯이 뭐고 어디다가 추가하시라는건지 이해가 가지 않습니다

**Comment by turtle85917** [comment]
아 서버 위젯이 뭔지 이미지를 올려드릴게요!

**Comment by wonderlandpark** [comment]
넣을 생각이 없습니다. 저희 사이트는 웹사이트 중심이지 디스코드 서버 중심이 아닙니다.

**Comment by turtle85917** [comment]
네
