### ISSUE TITLE
[TODO] 하트 시스템 개편

### ISSUE THREAD

**Issue by wonderlandpark** [koreanbots/koreanbots#93]
# 하트 시스템 개편

- 목적: 기존 하트 시스템은 고정적이며 1회 누른 뒤 변동이 없어 사이트 접속률을 유지하지 못함. (접속률 감소중)

- 변경사항:
```diff
- 일주일마다 하트 개수 초기화
+ 하트 쿨타임 12시간
```

- 기대효과: 봇끼리 활발한 경쟁 가능.

**Comment by samsunghappytree123** [comment]
1달마다 해서 이달의 봇 그런거 해도 괜찮을거같아요!

**Comment by wonderlandpark** [comment]
새로운 리라이트에서 적용될 예정입니다.

`v2.0`
