### ISSUE TITLE
오타수정 제안건

### ISSUE THREAD

**Issue by ArdanK0R** [koreanbots/koreanbots#94]
## 기능 설명
> https://koreanbots.dev/users/userid 에 있는
해당 유저에 개발하였거나, 관리하는 봇입니다. 를
해당 유저가 개발하였거나, 관리하는 봇입니다. 로 수정하는 것

## 필요한 이유
> 후자처럼 수정하는것이 더 자연스러워 보임.

## 기대 효과
> 상동.

## 확인
- [x] 중복되는 제안사항은 없나요?
- [x] 현실성 있는 제안인가요?

<!--
마크다운 체크박스 문법입니다.
[x] - 체크
[ ] - 체크하지 않음
으로 작성해주세요.
>

**Comment by turtle85917** [comment]
뭐가 다른거지..

**Comment by parangee** [comment]
BEFORE: 해당 유저**에** 개발하였거나, 관리하는 봇입니다
AFTER: 해당 유저**기** 개발하였거나, 관리하는 봇입니다

**Comment by wonderlandpark** [comment]
Minor한 typo 이슈이기에 이슈보단 PR 넣어주시면 좋을듯합니다. 그냥 두셔도 되고요.
그리고 제목은 꼭 작성해주세요.

**Comment by turtle85917** [comment]
아.. 에를 기로 바꾸자는 그 말이군요

**Comment by ArdanK0R** [comment]
> Minor한 typo 이슈이기에 이슈보단 PR 넣어주시면 좋을듯합니다. 그냥 두셔도 되고요.
> 그리고 제목은 꼭 작성해주세요.

네 알겠습니다.

**Comment by MoartMedia** [comment]
> 아.. 에를 기로 바꾸자는 그 말이군요

기가 아니라 가인거 같습니다.
순간 뭔가 했네요.

**Comment by wonderlandpark** [comment]
깃허브 이슈에서는 이슈에 대한 찬성, 거부 또는 내용 추가 등의 내용만 남겨주세요. 기타 토론은 디스코드 이용해주세요.

**Comment by wonderlandpark** [comment]
@ArdanKOR 말씀드렸지만 이슈 제목 추가해주세요.

**Comment by getsolaris** [comment]
해당 유저가 개발에 참여하였거나 관리하는 봇입니다.

`:name` 유저가 개발에 참여하였거나 관리하는 봇입니다.

**Comment by wonderlandpark** [comment]
https://github.com/koreanbots/client/pull/21 에서 수정되었습니다.
