### ISSUE TITLE
[제안] 위젯을 만들어주세요

### ISSUE THREAD

**Issue by kiki7000** [koreanbots/koreanbots#95]
## 기능 설명
> 어떤 기능인가요?

## 필요한 이유
> 해당 기능을 왜 추가해야하나요?

## 기대 효과
> 해당 기능을 추가하면 어떤 이점이 발생하나요?

## 확인
- [ ] 중복되는 제안사항은 없나요?
- [ ] 현실성 있는 제안인가요?

<!--
마크다운 체크박스 문법입니다.
[x] - 체크
[ ] - 체크하지 않음
으로 작성해주세요.
>

**Comment by kiki7000** [comment]
아 실수입니다

**Comment by turtle85917** [comment]
?
