### ISSUE TITLE
[버그] 봇의 정보를 수정할시 수정했다는 정보가 나와야만 합니다.

### ISSUE THREAD

**Issue by SaidBySolo** [koreanbots/koreanbots#96]
## 재현방법
> 어떻게하면 발생시킬 수 있나요?

1. 관리패널 접속
2. 봇에 ``관리하기`` 접속
3. 봇 정보를 수정후저장
4. 리다이렉트 되고 볼수있는 화면 관찰

## 예상되는 정상적인 동작
> 정상이라면 어떻게 되야하나요?

봇의 정보가 수정되었습니다 라는 문구가 떠야합니다.

https://koreanbots.dev/?message=editSuccess

해당 링크가 오류 추적에 도움이될거같습니다.

## 발생한 문제
> 어떤 문제가 발생하나요?

뜨지 않습니다.

## 클라이언트 버전
> 클라이언트 버전을 알려주세요!

[빌드 정보] 버전: 1.1.0 해시: 4b45fd261da9a564f8f7022ccf8c909dfb5b4798

## 사양
> OS 정보와 브라우저의 버전을 알려주세요!

Chrome 84

Windows 10 1909

## 확인
- [x] 중복되는 이슈는 없나요?
- [x] 해당 버그를 다시 발생시킬 수 있나요?

<!--
마크다운 체크박스 문법입니다.
[x] - 체크
[ ] - 체크하지 않음
으로 작성해주세요.
>

**Comment by SaidBySolo** [comment]
![image](https://user-images.githubusercontent.com/33891531/89103632-287c6500-d44e-11ea-9f48-cbe70d42e3bf.png)

**Comment by wonderlandpark** [comment]
Looks like its Too minor

**Comment by wonderlandpark** [comment]
Dupe of #93

**Comment by wonderlandpark** [comment]
Its intended behavior

**Comment by wonderlandpark** [comment]
NAB closing issue
