### ISSUE TITLE
[버그] 모듈에서 버그남.

### ISSUE THREAD

**Issue by turtle85917** [koreanbots/koreanbots#99]
## 기능 설명
> 어떤 기능인가요?

## 필요한 이유
> 해당 기능을 왜 추가해야하나요?

## 기대 효과
> 해당 기능을 추가하면 어떤 이점이 발생하나요?

## 확인
- [ ] 중복되는 제안사항은 없나요?
- [ ] 현실성 있는 제안인가요?

<!--
마크다운 체크박스 문법입니다.
[x] - 체크
[ ] - 체크하지 않음
으로 작성해주세요.
>

**Comment by wonderlandpark** [comment]
다시 한 번 무의미한 이슈를 생성하신다면 차단 처리하겠습니다.

**Comment by kijk2869** [comment]
이 레포지토리가 아닙니다. 트랜스퍼 해드릴게요.
추가로 스텍트레이스 첨부해주셔야합니다.
